### ISSUE TITLE
ETA Java: incorrect dependency for junit and commons-logging

### ISSUE THREAD

**Issue by addicticks-dev** [Refinitiv/Real-Time-SDK#111]
When ETA Java is used from Maven the **junit** library and **commons-logging** gets pulled in as transitive dependencies. This is incorrect. The ETA Java library doesn't depend on having junit  on the classpath (except for performing unit testing of course). Nor does it depend on commons-logging.

Please have a look [here](https://search.maven.org/artifact/com.thomsonreuters.upa/upa/3.3.1.0/jar) on what it looks like from the point of view of Maven Central. To be more precise the POM for ETA Core in Maven Central looks like this:
![2019-08-03 17_06_37-The Central Repository Search Engine](https://user-images.githubusercontent.com/15076120/62413689-218bfe00-b612-11e9-9343-eaf984695227.png)

I believe the root cause of the issue is the *allprojects* block in the overall `build.gradle` file.

**Comment by brettjbush** [comment]
@addicticks-dev thank you for notifying us of these dependencies. Our team is investigating.

**Comment by vlevendel** [comment]
@addicticks-dev Please reopen if this is still an issue.
