### ISSUE TITLE
ETA Java: Drop commons-codec dependency

### ISSUE THREAD

**Issue by addicticks-dev** [Refinitiv/Real-Time-SDK#112]
Now that Elektron-SDK Java no longer supports versions of Java prior to version 1.8 there is no longer a need for using the **commons-codec** library.

ETA Java uses commons-codec library for Base64 routines, but such routines are [now part of the JDK itself](https://docs.oracle.com/javase/8/docs/api/java/util/Base64.html) as of Java 1.8.

**Comment by brettjbush** [comment]
@addicticks-dev - thank you for raising this is dependency removal. Our team is investigating this issue as well.
