### ISSUE TITLE
cmake string(REPLACE ...) must always use quoted source

### ISSUE THREAD

**Issue by ned14** [Refinitiv/Real-Time-SDK#115]
The superbuild of Elektron-SDK-BinaryPack breaks if `CMAKE_MODULE_PATH` contains more than one item because of lack of quoting of source string in string replacement. To fix, for every instance like:

    string(REPLACE ";" "|" EXTERNAL_MODULE_PATH ${EXTERNAL_MODULE_PATH})

... you need to replace with:

    string(REPLACE ";" "|" EXTERNAL_MODULE_PATH "${EXTERNAL_MODULE_PATH}")

This is because otherwise `${EXTERNAL_MODULE_PATH}` is expanded, which converts the `;` into spaces, and thus the `|` is never inserted. This then breaks reconversion back to a cmake list.

**Comment by vlevendel** [comment]
@ned14 Please see question above.

**Comment by ned14** [comment]
I would assume Linux and Windows. It hardly matters for the above bug report, same problem applies to any platform.

**Comment by vlevendel** [comment]
Addressed with RTSDK-2.0.3.L1. Closing.
