### ISSUE TITLE
Support Source Directory attributes such as LoadFilter via EMAConfig / programmatic config

### ISSUE THREAD

**Issue by umernalla** [Refinitiv/Real-Time-SDK#119]
Please support additional Source Directory attributes such as LoadFilter via EMAConfig or programmatic config.

At present developers must publish their own Source Directory message to set the above - which is onerous for such an incremental requirement.

**Comment by vlevendel** [comment]
Thank you for making this enhancement request. This is now being tracked internally to be addressed in a future release.

**Comment by vlevendel** [comment]
Included with tag, Real-Time-SDK-2.0.1.L1.
