### ISSUE TITLE
EMA - Control log file generation

### ISSUE THREAD

**Issue by pparlapiano** [Refinitiv/Real-Time-SDK#121]
Hi,

when using the EMA (C++) Library for a server application, it is normally useful to enable the logs generation to file with standard level for the consumer(s) and provider(s) used.

However, the generated logs are always in the form <FileName>_pid.log (default: “emaLog_pid.log”). Even by changing the fileName in configuration, the pattern is always <configured_value>_pid.log.

With time, this causes the generation of several logs in the application's working directory (one for each instance of the application). Suppose for instance an application restarted on a daily basis.

Would it be possible to implement in EMA a rolling mechanism that limits the number of generated logs, or any other configurable mechanism to avoid generating always a different log name?

Thanks

Best Regards,
Paolo

**Comment by vlevendel** [comment]
@pparlapiano Thank you for letting us know. We are now tracking this issue as an enhancement request. It will be considered for a future release.

**Comment by vlevendel** [comment]
@pparlapiano This is addressed with RTSDK-2.0.3.L1. Please reopen or open a new issue if there are any concerns.
