### ISSUE TITLE
Frequent Tunnel stream disconnection with TRCC using EMA Java SDK 3.4.0.1 which is causing our service to publish prices at the start and then break.

### ISSUE THREAD

**Issue by joelmozhu** [Refinitiv/Real-Time-SDK#129]
StatusMsg
    streamId="5"
    domain="System Domain"
    privateStream
    state="Closed, Recoverable / Suspect / None / 'channel down.'"
    name="BNC_Tunnel"
    serviceId="10"
    serviceName="DDS_TRCE"
StatusMsgEnd

ClientName: ChannelCallbackClient
Severity: Warning
Text:    Received ChannelDownReconnecting event on channel BNC_Channel_1
RsslReactor @2c9a9fb1
RsslChannel @2e83a38d
Error Id 0
Internal sysError 0
Error Location Reactor.processWorkerEvent
Error text Ping error for channel: Lost contact with connection...
loggerMsgEnd

eeb5b26fc354     Text:    RDMLogin stream state was changed to suspect with status message
eeb5b26fc354   username <not set>
eeb5b26fc354   usernameType <not set>
eeb5b26fc354   State: Open/Suspect/None - text: ""

Also, while debugging the code, I encountered a wierd error message which states **Decoding of encoded object is not supported in same application** in the below code:

@Override
    public void onStatusMsg(StatusMsg statusMsg, OmmConsumerEvent consumerEvent) {
        logger.info("----- Status message ----");

        if (consumerEvent.handle() == tunnelStreamHandle && statusMsg.state().streamState() == OmmState.StreamState.OPEN) {
            ReqMsg loginRequest = createLoginRequest(statusMsg);
            logger.info("StatusMsg received, preparing to perform client login... tunnelStreamHandle={}, streamId={}", tunnelStreamHandle,
                statusMsg.streamId());
            // Send login request & get refresh events from login substream
            **loginSubStreamHandle.set(refinitivConsumer.registerClient(loginRequest, this, 1,** tunnelStreamHandle));
            healthy = true;
        } else {
            logger.warn("Could not open tunnel stream expectedTunnelHandle={}, eventTunnelHandle={}, streamState={}",
                tunnelStreamHandle,
                consumerEvent.handle(),
                statusMsg.state().streamState());
            healthy = false;
        }
    }

I have also attached additional service logs and emaj logs for your investigation.

Note: I ran the sample EMA consumer source code for posting data to TRCC with our service configuration(host, service_name, username, password and the RIC's plugged into the sample code) and it worked fine.

**Service_logs**
[Service_logs.txt](https://github.com/Refinitiv/Elektron-SDK/files/4227539/Service_logs.txt)

[emaj.log](https://github.com/Refinitiv/Elektron-SDK/files/4227536/emaj.log)
[emaj.log.2020-02-19.0.gz](https://github.com/Refinitiv/Elektron-SDK/files/4227537/emaj.log.2020-02-19.0.gz)

**Comment by IProkopenkoRef** [comment]
Hi Joel,
Issue could be split into three separate topics.
1. TRCE connectivity issue. 
Message below means application didn't receive ping response. Please contact TRCE team to check DDS_TRCE service status in case you still have ping issues
`Error text Ping error for channel: Lost contact with connection...`

2. At the moment both C++ and Java ESDK doesn't allow to decode object which was just encoded. 
`Decoding of just encoded object in the same application is not supported`
Object was created by an application so you should be aware what was inside the object. However it would be convenient to have decode feature especially for debugging purposes. Jira would be raised to address this enhancement request in one of the future releases.

3. Invalid handle issue from the service log is related to first topic
```
5f80c1e6f26a     ClientName: ItemCallbackClient
5f80c1e6f26a     Severity: Error
5f80c1e6f26a     Text:    Attempt to use invalid Handle on submit(PostMsg). Instance name='BNC_Consumer_1'.
f80c1e6f26a loggerMsgEnd
```
Connection was lost and handle for posting is not valid anymore. Application should reestablish connection to proceed with data posting

**Comment by vlevendel** [comment]
@joelmozhu Please let us know if you need to reopen after reading thru above explanations.
