### ISSUE TITLE
Ema/Eta Java 3.4.0.1: Package.getPackages()

### ISSUE THREAD

**Issue by FrankConstructor** [Refinitiv/Real-Time-SDK#130]
I noticed some changes introduced via https://github.com/Refinitiv/Elektron-SDK/commit/2020ce17bed5388e93f24a40eba10c7e405bd3d1.

For example https://github.com/Refinitiv/Elektron-SDK/blob/master/Java/Eta/Core/src/main/java/com/thomsonreuters/upa/codec/Codec.java has a static initializer looping via Package.getPackages() to get the actual package of the (very same) class.
The code is highly inefficient and could be simplified to Codec.class.getPackage().
There are also other classes using the loop approach.

Moreover, we experience NullPointerExceptions due to the JBoss 7.1.6 (Linux) we are using when Package.getPackages() is executed. Surely, not an Elektron problem but noteworthy.

**Comment by IProkopenkoRef** [comment]
FrankConstructor, proposed change would be considered for a future release. Please fill-in Refinitiv contributors form: https://github.com/Refinitiv/Elektron-SDK#contributing to get the process started

**Comment by FrankConstructor** [comment]
@IProkopenkoRef I do not understand why you deem my issue as contribution.
It is just an observation / problem report.

**Comment by IProkopenkoRef** [comment]
You've proposed solution and contribution form is required if you wish to keep your authorship. The change itself would be considered for a future release.

**Comment by FrankConstructor** [comment]
Well, I do not need authorship...

**Comment by IProkopenkoRef** [comment]
Thank you for the observation/problem report.  Since you prefer not to do a pull request, we will make your proposed change in a future release.  I appreciate you patience.

**Comment by FrankConstructor** [comment]
@IProkopenkoRef 
I see that Elektron-SDK-1.5.0.L1 has been released.
Sill, the Package.getPackages() loop is used in the code.
Do you have an idea for what release the change I proposed is planned?

**Comment by vlevendel** [comment]
@FrankConstructor This is address with tag, Real-Time-SDK-1.5.1.L1.
