### ISSUE TITLE
Duplicate FID in EMA Java View request returns all fields in Refresh Response message

### ISSUE THREAD

**Issue by wasin-waeosri** [Refinitiv/Real-Time-SDK#131]
This issue firstly found in Developer Q&A [EMA Batchview: Getting data for fields in updates that I did not specify post](https://community.developers.refinitiv.com/questions/54982/ema-batchview-getting-data-for-fields-in-updates-t.html). 

When application sends the View request with duplicate FID, the application receives all fields Refresh Response message from the API. This behavior does not occurs with low number FID such as 22 or 25.

Example Code (Consumer Example 360) that causes the problem.

ElementList view = EmaFactory.createElementList();
OmmArray array = EmaFactory.createOmmArray();
			
array.fixedWidth(2);
array.add(EmaFactory.createOmmArrayEntry().intValue(156));
array.add(EmaFactory.createOmmArrayEntry().intValue(156));

view.add(EmaFactory.createElementEntry().uintValue(EmaRdm.ENAME_VIEW_TYPE, 1));
view.add(EmaFactory.createElementEntry().array(EmaRdm.ENAME_VIEW_DATA, array));
			
consumer.registerClient(EmaFactory.createReqMsg().serviceName("ELEKTRON_DD").name("IBM.N").payload(view), appClient);

Or

ElementList view = EmaFactory.createElementList();
OmmArray array = EmaFactory.createOmmArray();
			
array.fixedWidth(2);
array.add(EmaFactory.createOmmArrayEntry().intValue(8927));
array.add(EmaFactory.createOmmArrayEntry().intValue(8927));

view.add(EmaFactory.createElementEntry().uintValue(EmaRdm.ENAME_VIEW_TYPE, 1));
view.add(EmaFactory.createElementEntry().array(EmaRdm.ENAME_VIEW_DATA, array));
			
consumer.registerClient(EmaFactory.createReqMsg().serviceName("ELEKTRON_DD").name("IBM.N").payload(view), appClient);

RSSL trace file are following:
[example360_View_trace1.txt](https://github.com/Refinitiv/Elektron-SDK/files/4243575/example360_View_trace1.txt)

EMA Java version: 1.4.0L1

**Comment by IProkopenkoRef** [comment]
Thank you for bringing this to our attention. We are investigating further.
