### ISSUE TITLE
EMA C++: Setting literal as status text with Login::LoginRefresh::state() is unsafe!

### ISSUE THREAD

**Issue by miczuc** [Refinitiv/Real-Time-SDK#135]
Hello. I noticed, that using the setter method Login::LoginRefresh::state() with a string literal for the status text parameter leads to a garbage value on the client when sending the RefreshMsg obtained from the LoginRefresh  to the connecting consumer.
The reason for this behaviour on a Linux gcc system is:
The setter method finally stores the c_str() -Pointer of the passed parameter of type 'const EmaString &'. (in LoginRefreshImpl::state(...)). However, if you call the setter with a string literal, a temporary EmaString object is constructed from the string literal because the method signature expects a 'const EmaString &'. However, later on, at the time of sending the refresh message, the temporary EmaString object implicitely constructed by parameter conversion is not valid anymore,
so the stored c_ptr() points to freed memory (to a location with undetermined bytes).
This leads to a garbage random value in the status text!
The workaround is to use an explicite EmaString object for setting the text, within the scope of the sending function.
This is a C++ beginner's error, please fix immediately.
Regards, Michael Zuck

**Comment by IProkopenkoRef** [comment]
@miczuc Thank you for bringing this to our attention. Will be fixed in further releases

**Comment by vlevendel** [comment]
@miczuc Tag, Real-Time-SDK-1.5.1.L1, addresses this issue. Please reopen as needed.
