### ISSUE TITLE
EMA C++: using data dictionary to fill EMA messages is not multi-thread-safe

### ISSUE THREAD

**Issue by miczuc** [Refinitiv/Real-Time-SDK#136]
Hello.

I programmed an interactive provider, that uses a dedicated thread per connected consumer to build up EMA messages and send them to the corresponding consumer.

Of course each thread uses it own message objects, of type RefreshMsg / UpdateMsg, with a FieldList therein.

However, if the code that fills the message objects is not lock-protected, the data sent to to the consumers get corrupted (the fields in the field list get random values). If there is a lock protection arround the code, which fills the (thread-individual!) message objects, everything works fine. Obviously it is not safe, to build (different!) messages at the same time in multiple threads. Why ?!?
You should expect, that using different message objects in different threads should not interfere  with each other.
But what you get are corrupted messages. This is just annoying.

Regards, Michael Zuck

**Comment by IProkopenkoRef** [comment]
Hi Michael.
EMA is a thread safe and aware API. However for the best efficiency and low memory usage multi-threaded user application should take care for message objects tread-safety by itself.
Multi-threaded application should use locking and deep copy mechanism for message consistency. Enhancements to make EMA fully thread-aware are not prioritized at the moment.

**Comment by miczuc** [comment]
Hello Iaroslav .

"EMA is a thread safe and aware API."
No, it's not. If it was, it would be possible to use different message objects in parallel in multiple threads without data corruption.

**Comment by vlevendel** [comment]
@miczuc 

Apologies for your challenges with EMA.  A Correction: EMA is a thread safe and aware API where mentioned as-such in documentation. EMA and ETA APIs are designed for highest performance - here are the options to safely do encoding & decoding:

For encoding, please create different message objects and use them in parallel in multiple threads.  Also, all OMM types for encoding a message must _not_ be shared across multiple threads.  For decoding, clone the message  objects from the callback to process in parallel.  Please let us know if you run into issues or have specific questions.

Please note that we will have EMA provider performance applications available in a future release that will provide some sample code.

**Comment by miczuc** [comment]
Hello. You wrote:
"For encoding, please create different message objects and use them in parallel in multiple threads."
I do exactly that, I described it in my  initial note. It does not work. The sent data gets corrupted. That is exactly the problem.
Sorry, this seems to be a waste of time ...

**Comment by miczuc** [comment]
Hello.

Today I had some time and had a deeper look at the problem, and found the cause.
It is not the parallel filling of the Refresh / Update messages, what causes the problem.
It is the simultaneous use of an object of class DataDictionary in multiple threads.
I use the method DataDictionary::getEntry() to obtain the field information in order to build up
a message dynamically from various input values. I realized, that the method
"const DictionaryEntry& DataDictionaryImpl::getEntry(Int32 fieldId) const"
reuses an internal member "mutable DictionaryEntry _dictionaryEntry"
and returns a reference to this member.
That of course is not multi-thread-safe.
The data in a DictionaryEntry reference obtained with getEntry() in one thread is changed, if another thread calls getEntry().
That's why my messages get corrupted.

Conclusion: querying field information from a DataDictionary object is not multi-thread-safe.
However, this is also a serious problem. One would expect, that querying read-only information is multi-thread-safe.

Regards, Michael

**Comment by vlevendel** [comment]
@miczuc  Please use getEntry(Int32 fieldId, DictionaryEntry& entry) instead.

**Comment by vlevendel** [comment]
@miczuc Please let us know if above recommendation works for you.
