### ISSUE TITLE
EmaConfigImpl.cpp uses xmlCleanupParser wrongly, can cause memory corruption in multithreaded programs

### ISSUE THREAD

**Issue by DuncanSands** [Refinitiv/Real-Time-SDK#147]
When you create an OmmConsumerConfig object, it creates a EmaConfigBaseImpl object.  The EmaConfigBaseImpl destructor, which is run every time an OmmConsumerConfig object is destroyed, is in Ema/Src/Access/Impl/EmaConfigImpl.cpp line 58:

```
EmaConfigBaseImpl::~EmaConfigBaseImpl()
{
        delete _pEmaConfig;

        xmlCleanupParser();

        if (_pProgrammaticConfigure)
                delete _pProgrammaticConfigure;
}

```

In particular, if multiple objects are being destroyed in parallel, then xmlCleanupParser() is being called in parallel.  Let's see what the libxml2 docs have to say:
```
Function: xmlCleanupParser

This function name is somewhat misleading. It does not clean up parser state, it cleans up memory allocated by the library itself.
It is a cleanup function for the XML library. It tries to reclaim all related global memory allocated for the library processing.
It doesn't deallocate any document related memory.
One should call xmlCleanupParser() only when the process has finished using the library and all XML/HTML documents built with it.
See also xmlInitParser() which has the opposite function of preparing the library for operations.
WARNING: if your application is multithreaded or has plugin support calling this may crash the application if another thread or a plugin is still using libxml2.
It's sometimes very hard to guess if libxml2 is in use in the application, some libraries or plugins may use it without notice.
In case of doubt abstain from calling this function or do it just before calling exit() to avoid leak reports from valgrind !
```
So it makes no sense to call this during destruction of individual objects.  Instead, I suggest you follow what the docs advise: either don't call xmlCleanupParser at all, or call it on exit.  In my case I noticed occasional memory corruption and tracked it down to multiple parallel calls to xmlCleanupParser.

**Comment by fogol** [comment]
@DuncanSands Thank you for bringing this to our attention. It will be fixed in further releases.

**Comment by vlevendel** [comment]
@DuncanSands Tag, Real-Time-SDK-1.5.1.L1, has a fix for this issue.
