### ISSUE TITLE
Null Pointer Exception ?

### ISSUE THREAD

**Issue by alexkhyde** [Refinitiv/Real-Time-SDK#148]
https://github.com/Refinitiv/Elektron-SDK/blob/master/Java/Eta/Core/src/main/java/com/thomsonreuters/upa/transport/ServerImpl.java line 284 (current master)

socketChannel = _srvrScktChannel.accept();

socketChannel is then used without a null return check. Is the expectation that this method should only ever be called either as blocking or using a selector such that we know there is a new socket/connection pending?

Thanks

**Comment by Patrick-Gourdet** [comment]
while(..)
  {
   ………..
   Set selected = selector.selectedKeys();
   Iterator itr = selected.iterator();
   while (itr.hasNext())
        dispatch((SelectionKey)(itr.next()); //starts separate threads 
   selected.clear(); //clear the keys from the set since they are already processed
  }
for (int i = 0; i < availableClients; ++i) {
       SocketChannel sc = _srvrScktChannel.accept();
      
}

**Comment by Patrick-Gourdet** [comment]
I agree and if I may be so bold to add to your suggestion, a selector would allow the majority of function to remain non-blocking.
Need of some new definitions but I took the freedom to put something together please correct me if I am off. 
 ` SelectionKey sk = _srvrScktChannel.register(selector, SelectionKey.OP_ACCEPT); 
   Set selected = selector.selectedKeys();                                                                                                                                                               
   Iterator itr = selected.iterator();
   while (itr.hasNext()){
       SelectionKey selectionKey = (SelectionKey)itr.next(); //starts separate threads 
       if(selectionKey.isAcceptable()) 
          java.nio.channels.SocketChannel socketChannel = (SocketChannel )selectionKey.channel;
} `

**Comment by APaias** [comment]
Hi @alexkhyde,
You are right. It is expected that ETA provider application will use either non-blocking mode with selector or blocking mode, the first approach is a preferable one. On EMA level non-blocking mode would be used by default. Please see ETA training Module_1a_Connect.
Thank you for raising the issue of potential NullPointerException. We will handle this case as an error in one of the future releases.
