### ISSUE TITLE
EMA Java - Unable to resume a stream that was opened in a paused state

### ISSUE THREAD

**Issue by bxpw** [Refinitiv/Real-Time-SDK#151]
This question was asked in the Refinitiv community forum https://community.developers.refinitiv.com/questions/64439/ema-java-how-do-i-resume-a-stream-that-was-opened.html

The problem is that after making the request below

`long handle = ommConsumer.registerClient(EmaFactory.createReqMsg().serviceName("XXX").name("EUR=").pause(true));`

the stream cannot be resumed later by invoking
`ommConsumer.reissue(EmaFactory.createReqMsg().pause(false).initialImage(false).interestAfterRefresh(true), handle);`

This could be related to #149 that there's a problem with `reissue`

Another problem with the register request is that the initial `RefreshMsg` is sill received, I'd expect to receive no `RefreshMsg` or `UpdateMsg` when `pause` is set. I then tried

`EmaFactory.createReqMsg().serviceName("XXX").name("EUR=").pause(true).initialImage(false)`

I got an exception `com.thomsonreuters.ema.access.OmmInvalidUsageExceptionImpl: Failed to open or modify item request. Reason: ReactorReturnCodes.INVALID_USAGE. Error text: Cannot submit new item request to watchlist with NO_REFRESH flag set.`

The use case is that I want to implement a standby client that pre-subscribes to some instruments using `pause` and there should be no `RefreshMsg` or `UpdateMsg`, when the client becomes active (e.g. wakes up from standby), it reissues requests without `pause` and starts receiving messages.

**Comment by APaias** [comment]
@bxpw, Thank you for noticing the issue with resuming paused stream. We have isolated the cause and will work to address this in a future release.

Please note that the PAUSE flag works to pause updates but you should still expect to get a refreshMsg.  Also, after this is fixed, please note that updates can't resume without having received the initial refresh.  So, when resuming data, you must set initialImage to true along with setting pause to false.

Here's the workaround:  Please send the request with initialImage(true) and pause(false).  Immediately after that, send a reissue with pause(true).
