### ISSUE TITLE
OmmConsumerImpl::registerClient implementation doesn't unlock mutex when exception is thrown

### ISSUE THREAD

**Issue by richardsimaging** [Refinitiv/Real-Time-SDK#152]
This piece of code causes our code to deadlock when attempting to terminate an OmmConsumer :
```
UInt64 OmmConsumerImpl::registerClient( const ReqMsg& reqMsg, OmmConsumerClient& ommConsClient,
                                        void* closure, UInt64 parentHandle )
{
	_userLock.lock();

	UInt64 handle = _pItemCallbackClient ? _pItemCallbackClient->registerClient( reqMsg, ommConsClient, closure, parentHandle ) : 0;

	_userLock.unlock();

	return handle;
}
```

The problem here is that `_userLock` will not be unlocked if `_pItemCallbackClient->registerClient` is called and throws an exception (e.g. because`parentHandle` is invalid). 

There are a number of similar issues in that same source file, where the RAII pattern has not been used for acquiring/releasing locks.

Darren Richards.

**Comment by richardsimaging** [comment]
Having looked through the EMA source I suspect the fix for this code would look like this :
```
UInt64 OmmConsumerImpl::registerClient( const ReqMsg& reqMsg, OmmConsumerClient& ommConsClient,
                                        void* closure, UInt64 parentHandle )
{
	MutexLocker lock( _userLock );

	UInt64 handle = _pItemCallbackClient ? _pItemCallbackClient->registerClient( reqMsg, ommConsClient, closure, parentHandle ) : 0;

	return handle;
}
```

**Comment by fogol** [comment]
@richardsimaging Thank you for bringing this to our attention. It will be fixed in further releases.

**Comment by richardsimaging** [comment]
This problem is rather widespread in the EMA code and we had to use the Error Client callback mechanism because there are many functions that don't seem to be implemented correctly unlock after an exception is thrown. 

I regret choosing to use this wrapper instead of just using ETA and our own code. 

void OmmBaseImpl::submit( const PostMsg& postMsg, UInt64 handle )
{
	_userLock.lock();

	if ( _pItemCallbackClient ) _pItemCallbackClient->submit( postMsg, handle );

	_userLock.unlock();
}

Is this scheduled to be fixed at all ? Or is this a self-service offering ?

Thank you.

**Comment by vlevendel** [comment]
@richardsimaging This Jira will be in an upcoming push.  We're actively working on it and will only publish the fix after adequate testing and performance evaluation.
