### ISSUE TITLE
EMA C++: Error in DirectoryHandler when using more than 5 services

### ISSUE THREAD

**Issue by miczuc** [Refinitiv/Real-Time-SDK#153]
Hello.

I built an interactive provider, using the C++ Elektron SDK 1.4.0.
When the number of \<Service\> elements in the \<Directory\> element in the configuration file EmaConfig.xml exceeds 5,
a connecting consumer hangs on login and the provider reports the following error:

loggerMsg
    TimeStamp: 13:33:18.101
    ClientName: DirectoryHandler
    Severity: Error
    Text:    Internal error: failed to encode RsslRDMDirectoryMsg in DirectoryHandler::handleDirectoryRequest()
        Client handle 42787824
        Instance Name Provider_elisa_1Error Id -21
        Internal sysError 0
        Error Location /local/jenkins/workspace/ESDKCore_RCDEV/OS/OL7-64/rcdev/source/esdk/Cpp-C/Eta/Impl/RDM/rsslRDMDirectoryMsg.c:539
        Error Text (ret = rsslEncodeElementEntry(pEncodeIter, &elementEntry, &pState->serviceState)) == RSSL_RET_SUCCESS
loggerMsgEnd

I had a look at the source code in DirectoryHandler.cpp and found out, what happens:
In method DirectoryHandler::handleDirectoryRequest() there is a loop 

while (retCode == RSSL_RET_BUFFER_TOO_SMALL)

for increasing the buffer, where retCode is the return value of rsslEncodeRDMDirectoryMsg(...).

However, that loop is never entered, because retCode is set to -1, which differs from RSSL_RET_BUFFER_TOO_SMALL = -21.
But the value of rsslErrorInfo.rsslError.rsslErrorId is set to RSSL_RET_BUFFER_TOO_SMALL.
So you could use instead this loop condition:
while (rsslErrorInfo.rsslError.rsslErrorId == RSSL_RET_BUFFER_TOO_SMALL)

However, if you do so, there is another error in the interior of this loop:
After reallocation you have a new buffer address, however it is not updated in the _rsslEncodeIter object,
which still holds the old buffer address.

A new call of rsslSetEncodeIteratorBuffer(&_rsslEncodeIter, &rsslBuffer) is necessary after buffer reallocation
to set the correct buffer address.

Exactly the same errors appear in DirectoryHandler::sendDirectoryReject().

Regards, Michael Zuck

**Comment by fogol** [comment]
@miczuc Thank you for bringing this to our attention. It will be fixed in further releases.

**Comment by vlevendel** [comment]
Fix is included with tag, Real-Time-SDK-2.0.1.L1.

**Comment by miczuc** [comment]
Hello.

I had a look at the source code of DirectoryHandler.cpp, version 2.2.0.
There is still nonsense code (line 484 and line 690 + following while-block):

	retCode = rsslEncodeRDMDirectoryMsg(&_rsslEncodeIter, (RsslRDMDirectoryMsg*)&_rsslRdmDirectoryMsg.status, &rsslBuffer.length, &rsslErrorInfo);

	while (retCode == RSSL_RET_BUFFER_TOO_SMALL)
	{
        ...
        }
        
The function rsslEncodeRDMDirectoryMsg() returns either RSSL_RET_SUCCESS ( = 0) or RSSL_RET_FAILURE ( = -1).
Therefore the condition in the while-block is nonsense. I wrote this already in my original post. Did you read it ???

Regards, Michael Zuck

**Comment by miczuc** [comment]
Addendum: I tested with 7 services in EmaConfig.xml. The while-loop is entered once and left again.
In fact the first call of  rsslEncodeRDMDirectoryMsg() returns  RSSL_RET_BUFFER_TOO_SMALL.
The error does not appear anymore, problem is solved.

Regards, Michael Zuck
