### ISSUE TITLE
CentOS 8 support

### ISSUE THREAD

**Issue by morris-pete** [Refinitiv/Real-Time-SDK#154]
Can you tell me if there is a timeline for validation against CentOS 8.x? And for that matter, the Readme.md only appears to reference RHEL6.x, not RHEL8.x,

**Comment by fogol** [comment]
@morris-pete  CentOS 8.x support is planned in the next release. It is expected in the middle of October.

**Comment by fogol** [comment]
@morris-pete Would you mind to try the latest release?

Please, look at Readme.md updated for Cpp-C :

https://github.com/Refinitiv/Real-Time-SDK/tree/master/Cpp-C

Supported Platforms, OSs, Compilers
- CentOS 8.X Release 64-bit

Linux
Platforms & Compilers:
- GCC compiler suite version 8.3.1 or higher for CentOS 8.0, 64-bit, qualification with RH8 library build
