### ISSUE TITLE
C files in Eta/Impl/Converter have suffix .C rather than .c

### ISSUE THREAD

**Issue by DuncanSands** [Refinitiv/Real-Time-SDK#155]
For some reason the files in Eta/Impl/Converter have suffix .C (upper case), while everywhere else in Eta it is .c (lower case).  For example jsonToRsslMsgDecoder.C.   I'm guessing that you are using Windows, where case doesn't matter, but we are on Linux where it does matter.  Because of the .C, our build system thinks that these files are written in C++.  While we can teach our build system that in this case .C means C not C++, there seems to be no good reason for you to use .C here, so can you please change .C to .c in this directory.

**Comment by DuncanSands** [comment]
Sorry - looks like these files really are C++ files, so can you please use .cpp like all the other C++ files.

**Comment by fogol** [comment]
@DuncanSands Thank you for bringing this to our attention. It is known issue. Build system thinks that these files are written in C++ because of cmake. We will discuss if we are going to fix it and when and then I will update a status of the issue.

**Comment by fogol** [comment]
@DuncanSands We've discussed this issue: The .C extension is used in standard C++. So, this issue will not be fixed.

**Comment by DuncanSands** [comment]
Fair enough, thanks for looking into it.
