### ISSUE TITLE
Extraneous space before REAL_SHA1_INIT

### ISSUE THREAD

**Issue by DuncanSands** [Refinitiv/Real-Time-SDK#156]
I noticed that when building the Eta libraries on Linux, this turns up on the build line: "-D REAL_SHA1_INIT".  Probably this should be -DREAL_SHA1_INIT, the difference being caused by an unwanted space before REAL_SHA1_INIT.

**Comment by fogol** [comment]
@DuncanSands Thank you for bringing this to our attention. It will be fixed in further releases.
