### ISSUE TITLE
Invalid conversion between char and char* in rwfToJsonConverter.cpp

### ISSUE THREAD

**Issue by DuncanSands** [Refinitiv/Real-Time-SDK#157]
Noticed by recent g++.  Probably you are trying to get a null pointer here, in which case the patch below fixes it.

--- a/Eta/Impl/Converter/rwfToJsonConverter.cpp
+++ b/Eta/Impl/Converter/rwfToJsonConverter.cpp
@@ -17,8 +17,8 @@

 #include "rtr/rwfToJsonConverter.h"

-DEV_THREAD_LOCAL char* rwfToJsonConverter::_elementSetDefDbMem = (char)0x0;
-DEV_THREAD_LOCAL char* rwfToJsonConverter::_fieldSetDefDbMem = (char)0x0;
+DEV_THREAD_LOCAL char* rwfToJsonConverter::_elementSetDefDbMem = 0;
+DEV_THREAD_LOCAL char* rwfToJsonConverter::_fieldSetDefDbMem = 0;

 //Use 1 to 3 byte variable UTF encoding
 //#define MaxUTF8Bytes 3

**Comment by fogol** [comment]
@DuncanSands Thank you for bringing this to our attention. It will be fixed in further releases.
