### ISSUE TITLE
[EMA C++] Problem with XmlTraceToMultipleFiles for programmatic configuration of a NiProvider

### ISSUE THREAD

**Issue by Eucalyptus2013** [Refinitiv/Real-Time-SDK#162]
Hello,

When I do a programmatic configuration of a NiProvider, I set XmlTraceMaxFileSize to 100000 and XmlTraceToMultipleFiles to 1 with:

.addInt("XmlTraceMaxFileSize", 100000)

and

.addUInt("XmlTraceToMultipleFiles", 1)

Size is in bytes so I should get a new file if the file size exceeds 100KB.

It is working correctly, I get several files with size less than 100KB.

Now if I change .addUInt("XmlTraceToMultipleFiles", 1) to .addUInt("XmlTraceToMultipleFiles", 0), from the configuration guide, I expect that "0 (false): the Enterprise Message API stops writing the XML trace if the current file reaches the XmlTraceMaxFileSize. ".

So I should have only one file less than 100 KB.

It is not working correctly. I got one file that continues to be written even if the file size exceeds 100 KB.

**Comment by MitchellKato** [comment]
Thank you for raising this.  This definitely looks like there is an issue with the XML trace functionality where we're not stopping the write correctly.

I have raised a JIRA for this, and it will be fixed in a future release.

**Comment by vlevendel** [comment]
@Eucalyptus2013 This is addressed with RTSDK-2.0.3.L1. Please reopen or open a new issue if there are any concerns.
