### ISSUE TITLE
VAConsumer login example code

### ISSUE THREAD

**Issue by andysCaplin** [Refinitiv/Real-Time-SDK#164]
In the VAConsumer login example code file - https://github.com/Refinitiv/Real-Time-SDK/blob/master/Cpp-C/Eta/Applications/Examples/VAConsumer/rsslLoginConsumer.c - when a refresh( RDM_LG_MT_REFRESH ) message is received the channel is closed if the streamState is not open

```
		if (pState->streamState != RSSL_STREAM_OPEN)
		{
			printf("\nLogin attempt failed\n");
			closeConnection(pReactor, pChannel, pCommand);
			return RSSL_RC_CRET_SUCCESS;
		}
```

Shouldn't the same thing be done when a RDM_LG_MT_STATUS message is received - if the streamState is not open.

**Comment by dmykhailishen** [comment]
@andysCaplin 
Thank you for your report. This will be fixed in further releases.
