### ISSUE TITLE
Not able to build Elektron SDK (ESDK) for 32-bit platform

### ISSUE THREAD

**Issue by pawan-jha** [Refinitiv/Real-Time-SDK#166]
Hi Team
I have downloaded ESDK package(Elektron-SDK-1.5.0.L1.linux) and I am trying to build ESDK package for 32-bit support.
**_Command used to build ESDK : cmake -Hesdk -Bbuild-esdk -DBUILD_32_BIT_ETA=ON
Build Server :               GNU/Linux x86_64 3.10.0-1127.el7.x86_64_**

I am getting below error while building ESDK package for 32-bit support (Find the attached build log files).

[100%] Completed 'cjson'
[100%] Built target cjson
Prebuilt libraries not found: librssl_LIBRARY_OPTIMIZED-NOTFOUND, in
/home/p/pawank/Elektron-SDK-1.5.0.L1.linux/setup/esdk/Cpp-C/Eta/Libs/LIN3_32_GNU485/Optimized;/home/p/pawank/Elektron-SDK-1.5.0.L1.linux/setup/esdk/Cpp-C/Eta/Libs/LIN3_32_GCC485/Optimized
Prebuilt libraries not found: librssl_shared_LIBRARY_OPTIMIZED-NOTFOUND, in
/home/p/pawank/Elektron-SDK-1.5.0.L1.linux/setup/esdk/Cpp-C/Eta/Libs/LIN3_32_GNU485/Optimized;/home/p/pawank/Elektron-SDK-1.5.0.L1.linux/setup/esdk/Cpp-C/Eta/Libs/LIN3_32_GCC485/Optimized
Prebuilt libraries not found: librsslJsonConverter_shared_LIBRARY_OPTIMIZED-NOTFOUND, in
/home/p/pawank/Elektron-SDK-1.5.0.L1.linux/setup/esdk/Cpp-C/Eta/Libs/LIN3_32_GNU485/Optimized;/home/p/pawank/Elektron-SDK-1.5.0.L1.linux/setup/esdk/Cpp-C/Eta/Libs/LIN3_32_GCC485/Optimized
Prebuilt libraries not found: librsslVA_LIBRARY_OPTIMIZED-NOTFOUND, in
/home/p/pawank/Elektron-SDK-1.5.0.L1.linux/setup/esdk/Cpp-C/Eta/Libs/LIN3_32_GNU485/Optimized;/home/p/pawank/Elektron-SDK-1.5.0.L1.linux/setup/esdk/Cpp-C/Eta/Libs/LIN3_32_GCC485/Optimized
Prebuilt libraries not found: librsslVA_shared_LIBRARY_OPTIMIZED-NOTFOUND, in
/home/p/pawank/Elektron-SDK-1.5.0.L1.linux/setup/esdk/Cpp-C/Eta/Libs/LIN3_32_GNU485/Optimized;/home/p/pawank/Elektron-SDK-1.5.0.L1.linux/setup/esdk/Cpp-C/Eta/Libs/LIN3_32_GCC485/Optimized
Prebuilt libraries not found: libansi_LIBRARY_OPTIMIZED-NOTFOUND, in
/home/p/pawank/Elektron-SDK-1.5.0.L1.linux/setup/esdk/Cpp-C/Eta/Libs/LIN3_32_GNU485/Optimized;/home/p/pawank/Elektron-SDK-1.5.0.L1.linux/setup/esdk/Cpp-C/Eta/Libs/LIN3_32_GCC485/Optimized
-- Skipping Eta Doxygen Build: BUILD_ETA_DOXYGEN:OFF
-- Skipping Ema Library Build: BUILD_EMA_LIBRARY:OFF
-- Configuring incomplete, errors occurred!
**_Can you please tell me how to get rid of this error and take a 32-bit successful build for ESDK ?
Also is it possible to download compiled 32-bit Elektron SDK (ESDK) package?_**
[build.log](https://github.com/Refinitiv/Real-Time-SDK/files/5696418/build.log)
[CMakeOutput.log](https://github.com/Refinitiv/Real-Time-SDK/files/5696419/CMakeOutput.log)

_**

**Comment by MitchellKato** [comment]
We do not provide a pre-built 32-bit Real Time SDK package.  If you wish to build a 32-bit build, please make sure that you're building from the github repository, not the pre-compiled distribution provided from the Refinitiv developer's portal.

In addition, EMA is a 64-bit library only.

**Comment by pawan-jha** [comment]
Hi @MitchellKato 
Thanks for the Information.
_Can you please tell me how to get the SDK package from  github repository and build 32-bit build ?_

**Comment by MitchellKato** [comment]
You will need to clone the RTSDK package from this github repo, and build instructions are provided in this doc:
https://github.com/Refinitiv/Real-Time-SDK/blob/master/Cpp-C/Eta/Docs/RTSDK_C_Installation_Guide.pdf

**Comment by pawan-jha** [comment]
Hi @MitchellKato 
Thanks for the Info.

**_We can build EMA and ETA both for 32-bit platform ??_**
My application needs 32-bit EMA API. **_ So can we build 32-bit EMA API  using cmake from  RTSDK package ??_**

**Comment by MitchellKato** [comment]
EMA is a 64-bit only library.  It cannot be built as a 32-bit library.  ETA can be built as 32-bit with a clone of the RTSDK repository.

**Comment by pawan-jha** [comment]
Thanks a lot @MitchellKato
