### ISSUE TITLE
EMA C++:  configuration parameters ConnectionPingTimeout / ConnectionMinPingTimeout are applied as number of seconds, not milliseconds

### ISSUE THREAD

**Issue by miczuc** [Refinitiv/Real-Time-SDK#168]
Hello.

I was wondering (once again) about the values shown in the toString() method of ChannelInformation, this time for
parameter "ping timeout". The value 255 is always displayed, no matter, what the client (e.g. rdmstestclient) specifies for its ping timeout. I had a look at the source code. Obviously the values are passed as are to the rssl layer, but that treats them as
number of seconds. In the EMA configuration guide you can read, the parameter values are in milliseconds.
This is obviously wrong. Also the defaults values in the code ( ActiveConfig.h )
#define DEFAULT_CONNECTION_PINGTIMEOUT                                  60000
#define DEFAULT_CONNECTION_MINPINGTIMEOUT                               20000
do not make sense for the rssl layer values, which are measured in seconds.

This bug is in EMA version 1.4.0 and also in EMA 1.5.1 , for higher versions I don't know.

Regards, Michael

**Comment by fogol** [comment]
@miczuc Thank you for bringing this to our attention. I see the root of the issue. It will be fixed in further releases.
