### ISSUE TITLE
Support request messages using the permid rather than the RIC

### ISSUE THREAD

**Issue by DuncanSands** [Refinitiv/Real-Time-SDK#169]
For some instruments the RIC code shifts about quite often.  For example, for Australian stocks the RIC changes whenever there is an upcoming dividend and changes back once the dividend has been issued.  This means that in order to subscribe to market data you somehow have to know about all such RIC changes in a timely fashion.  The permid is a much more stable identifier (it basically represents the chain of RICs, for example for Australian stocks it is constant while the RIC jumps about due to dividends).  So it would be neat to be able to subscribe to market data using the permid.  Any chance of implementing this?

**Comment by vlevendel** [comment]
@DuncanSands This is not an RTSDK question.  Please post this question to [Developer Portal](https://developers.refinitiv.com/en).
