### ISSUE TITLE
Buggy code in rsslRDMDictionaryMsg.c

### ISSUE THREAD

**Issue by rpbice** [Refinitiv/Real-Time-SDK#170]
Line 232 doesn't look right (boolean && operator):

if (!key || !(key->flags && RSSL_MKF_HAS_NAME) || !(key->flags && RSSL_MKF_HAS_FILTER) || !(key->flags && RSSL_MKF_HAS_SERVICE_ID))

**Comment by fogol** [comment]
@rpbice Thank you for bringing this to our attention. It will be fixed in further releases.
