### ISSUE TITLE
EMA C++ Websocket example mismatch between Readme and source code

### ISSUE THREAD

**Issue by umernalla** [Refinitiv/Real-Time-SDK#172]
The example RTSDK-2.0.1.L1.win.rrg\Cpp-C\Ema\Examples\Training\IProvider\100_Series\180_MP_Websocket\IProvider.cpp

the readme.txt refers to 'Provider_2' whereas the source code uses 'Provider_3'

The Java Readme and source code match with 'Provider_3'

**Comment by fogol** [comment]
@umernalla Thank you for bringing this to our attention. It will be fixed in further releases.
