### ISSUE TITLE
OmmConsumerConfig.clientId() not mentioned in EMACPP_ConfigGuide.pdf section 4.4.1

### ISSUE THREAD

**Issue by umernalla** [Refinitiv/Real-Time-SDK#173]
A customer was using the EMACPP_ConfigGuide.pdf to figure out how to set his ClientID in the config.

https://github.com/Refinitiv/Real-Time-SDK/blob/master/Cpp-C/Ema/Docs/EMACPP_ConfigGuide.pdf

He noted that OmmConsumerConfig.clientId() is not mentioned in the above doc, whilst password() and username() are - which caused some confusion for him.

I also note that section 4.4.1.2 heading is a bit vague and does not mention ProviderConfig

Can we please get these changed in a future release?

Thanks

**Comment by fogol** [comment]
@umernalla Thank you for bringing this to our attention. It will be fixed in further releases.

**Comment by vlevendel** [comment]
@umernalla 

We do not permit users to specify RTO credentials like username, password and clientID via EmaConfig.xml.  RTO uses RDM_LOGIN_USER_AUTHN_TOKEN type to authenticate. The parameters mentioned in the current configuration guides populate "Name" in Login Request Key and Password elementEntry in Login Request Body - see sample below.  These are used for [other forms of authentication](https://github.com/Refinitiv/Real-Time-SDK/blob/master/Cpp-C/Eta/Include/Codec/rtr/rsslRDM.h#L223) other than RTO. 

Sample Login Request:
<requestMsg domainType="RSSL_DMT_LOGIN" streamId="1" containerType="RSSL_DT_NO_DATA" flags="0x4 (RSSL_RQMF_STREAMING)" dataSize="0">
    <key  flags="0x26 (RSSL_MKF_HAS_NAME|RSSL_MKF_HAS_NAME_TYPE|RSSL_MKF_HAS_ATTRIB)"  name="**username**" nameType="1" attribContainerType="RSSL_DT_ELEMENT_LIST">
        <attrib>
            <elementList flags="0x8 (RSSL_ELF_HAS_STANDARD_DATA)">
                <elementEntry name="ApplicationId" dataType="RSSL_DT_ASCII_STRING" data="256"/>
                <elementEntry name="ApplicationName" dataType="RSSL_DT_ASCII_STRING" data="rsslConsumer"/>
                <elementEntry name="Position" dataType="RSSL_DT_ASCII_STRING" data="10.185.225.149/net"/>
                <elementEntry name="Password" dataType="RSSL_DT_ASCII_STRING" data="**mypassword**"/>
                <elementEntry name="ProvidePermissionProfile" dataType="RSSL_DT_UINT" data="1"/>
                <elementEntry name="ProvidePermissionExpressions" dataType="RSSL_DT_UINT" data="1"/>
                <elementEntry name="SingleOpen" dataType="RSSL_DT_UINT" data="1"/>
                <elementEntry name="AllowSuspectData" dataType="RSSL_DT_UINT" data="1"/>
                <elementEntry name="InstanceId" dataType="RSSL_DT_ASCII_STRING" data="instance1"/>
                <elementEntry name="Role" dataType="RSSL_DT_UINT" data="0"/>
                <elementEntry name="DownloadConnectionConfig" dataType="RSSL_DT_UINT" data="0"/>
            </elementList>
        </attrib>
    </key>
    <dataBody>
    </dataBody>
</requestMsg>

To understand how to connect to RTO, please see EMA examples [113 ](https://github.com/Refinitiv/Real-Time-SDK/blob/master/Cpp-C/Ema/Examples/Training/Consumer/100_Series/113_MP_SessionMgmt/Consumer.cpp) or [450](https://github.com/Refinitiv/Real-Time-SDK/blob/master/Cpp-C/Ema/Examples/Training/Consumer/400_Series/450_MP_QueryServiceDiscovery/Consumer.cpp).  

Disclaimer:  Credentials must be securely stored by applications written to EMA/ETA and provided as inputs to the API when/as required to connect to RTO.

**Comment by umernalla** [comment]
Hi @vlevendel 
Thanks for the update. 
Just to clarify, I am aware that you cannot specify credentials in the EMAConfing.xml.
However, the point the customer was making is that the documentation is not complete. 
Under section **4.4.1.1** **OmmConsumerConfig Class Function Calls**, it mentions the other credential related parameters and that they don't have a default value - but it does not mention clientId().
Thanks.

**Comment by vlevendel** [comment]
@umernalla  I have clarified above further in the PDF docs.

**Comment by vlevendel** [comment]
New PDFs are included with Real-Time-SDK-2.0.2.L1.
