### ISSUE TITLE
[EMA] [Java] ProgrammaticConfigure convertToEnum emits error for RSSL_SOCKET

### ISSUE THREAD

**Issue by MaciekSipior** [Refinitiv/Real-Time-SDK#177]
Missing else:
https://github.com/Refinitiv/Real-Time-SDK/blob/1541de00c63e0a4f3706e3f2f30d218f0e85a240/Java/Ema/Core/src/main/java/com/refinitiv/ema/access/ProgrammaticConfigure.java#L2840

Any ServerType value other than RSSL_ENCRYPTED will cause an error in log.

Should be this instead:
`			if(enumValue.equals("RSSL_SOCKET") || enumValue.equals("RSSL_WEBSOCKET"))
				serverType = ConnectionTypes.SOCKET;
			else if(enumValue.equals("RSSL_ENCRYPTED"))
				serverType = ConnectionTypes.ENCRYPTED;
			else`

**Comment by vlevendel** [comment]
Thank you @MaciekSipior.  This will be resolved in our upcoming release.

**Comment by vlevendel** [comment]
Fix is included with Real-Time-SDK-2.0.2.L1.
