### ISSUE TITLE
Desktop Viewer fails if using an EMA Configuration file

### ISSUE THREAD

**Issue by umernalla** [Refinitiv/Real-Time-SDK#178]
Gradlew runrrtviewerdesktop
Tick the Use EMA Configuration file option,
select the EMAConfig.xml found in Java folder and the error message is show:
2021-07-16 09:41:05.789 SEVERE  com.refinitiv.ema.access.ChannelCallbackClient initializeReactor 
loggerMsg
    ClientName: ChannelCallbackClient
    Severity: Error
    Text:    Failed to add RsslChannel(s) to RsslReactor. Channel name(s) 
	Instance Name Consumer_RRTViewer_DE_5
	RsslReactor @21579321
	RsslChannel null
	Error Id -1
	Internal sysError 0
	Error Location RestReactor.submitServiceDiscoveryRequestBlocking
	Error Text Failed to request service discovery information. Text: 404 page not found
loggerMsgEnd

If an EMA Config file is not used, it works OK.

**Comment by fogol** [comment]
@umernalla Thank you for bringing this to our attention. We will investigate the issue. It will be fixed in further releases.

**Comment by vlevendel** [comment]
@umernalla This is addressed with RTSDK-2.0.3.L1.
