### ISSUE TITLE
Documentation error in EMA Java Config guide

### ISSUE THREAD

**Issue by umernalla** [Refinitiv/Real-Time-SDK#179]
The document https://github.com/Refinitiv/Real-Time-SDK/blob/master/Java/Ema/Docs/EMAJ_ConfigGuide.pdf
lists the following ChannelType values:
RSSL_SOCKET
• RSSL_ENCRYPTED
• RSSL_HTTP
• WEBSOCKET
However, if you use WEBSOCKET, the following error is generated:

SEVERE: loggerMsg
    ClientName: EmaConfig
    Severity: Error
    Text:    no implementation in convertEnum for enumType [WEBSOCKET]
loggerMsgEnd

If I change to RSSL_WEBSOCKET (as per the CPP guide) then it's fine.

I suspect the same issue may apply in section _3.3.6 Parameters for Use with Channel Types: RSSL_ENCRYPTED_ ?

**Comment by umernalla** [comment]
Also, for both the EMAJava and EMA CPPP config guides, in section _4.4.2 Using the host() Function: How “Host” and “Port” are Processed_ - can we point to that setting port to 15000 in the  Host value changes the ChannelType to RSSL_WEBSOCKET - that seems to be what I experienced...

**Comment by fogol** [comment]
@umernalla Thank you for bringing this to our attention. It will be fixed in further releases.

**Comment by vlevendel** [comment]
@umernalla This is addressed with RTSDK-2.0.3.L1.
