### ISSUE TITLE
Build files ignore binary pack during build

### ISSUE THREAD

**Issue by orycho** [Refinitiv/Real-Time-SDK#180]
Hi All,

we are on Linux and are following the directions (Windows is not used on our servers). 
One thing that is missing is lsb_release which may be related, but I doubt it.
 
The issue is this: our build environment uses a chroot based approach to prevent access to the system libraries. 
This is done in order to build binaries which are independent (that is also why it does not like shared libraries).
 
So when the source code refers to headers that are not part of the standard library, like zlib in this example, it does not find it: it not present in the chrooted environment. The build must use those headers and libraries actually provided by the binary pack.
 
That however is not being done. I presume you never encountered this issue as your build finds the system libraries/headers and thus does not care about those coming with the OS.

The error message is
[  1%] Building C object lib/CMakeFiles/libcurl.dir/version.c.o
/home/oliebman/Refinitiv/Real-Time-SDK-2.0.2.L1/build/external/BUILD/curl/source/lib/version.c:69:10: fatal error: zlib.h: No such file or directory
   69 | #include <zlib.h>
      |          ^~~~~~~~
compilation terminated.
 
Despite the zlib.h file being present in the binary pack. So the directories (thus headers and libraries) from the binary pack are not used by the build process.

We would really like to build from source, without having to depend on headers and libraries being in the system directories.

Thanks,
Ory (for FactSet: ory.chowawliebman@factset.com)

**Comment by vlevendel** [comment]
The problem is that curl can't find a zlib header.  Please setup your CMake environment to include the header files our build includes. This is not something we can fix -- we already make the header file available.  Please let us know if you have further questions.  

Ref:5479
