### ISSUE TITLE
FR: add asBigDecimal() to OmmReal iface

### ISSUE THREAD

**Issue by dkhokhlov** [Refinitiv/Real-Time-SDK#182]
Feature request:
- add asBigDecimal() to OmmReal iface

Reasoning:
- to have simple way to get more precise numeric representation of rational value stored in OmmReal in addition to existing  imprecise asDouble().

**Comment by fogol** [comment]
@dkhokhlov Thank you for bringing this to our attention. We will add it in future releases.

**Comment by vlevendel** [comment]
RTSDK-2.0.5.L1 addresses this issue. Please reopen if there are further concerns.
