### ISSUE TITLE
More Memory leak issue after upgrade to RTO from EZD

### ISSUE THREAD

**Issue by hao-tang-Refinitiv** [Refinitiv/Real-Time-SDK#183]
![12183-498501245](https://user-images.githubusercontent.com/91595134/135241747-688a53f8-b1d7-4408-947d-e946b2e24813.jpg)

**Comment by hao-tang-Refinitiv** [comment]
Beijing Bytedance Technology Co., Ltd

More Memory leak issue after upgrade to RTO from EZD, Please see attached snapshot

021-09-26T10:44:06.449+0800: 315081.259: [GC cleanup 3737M->3737M(4096M), 0.0052791 secs]
[Times: user=0.07 sys=0.00, real=0.00 secs][](url)

Machine ID: GE-A-01454540-3-7608

**Comment by vlevendel** [comment]
Closing due to lack of enough information solicited directly.
