### ISSUE TITLE
Cpp-C/Eta/Applications/Examples/Provider/rsslItemHandler.c processItemRequest - does not return RSSL_RET_FAILURE

### ISSUE THREAD

**Issue by umernalla** [Refinitiv/Real-Time-SDK#186]
Hi,
I noticed that in Cpp-C/Eta/Applications/Examples/Provider/rsslItemHandler.c function processItemRequest() - it does not return RSSL_RET_FAILURE when an Unhandled Item Msg Class is received (line 1204)

However, for the Java equivalent Java/Eta/Applications/Examples/src/main/java/com/refinitiv/eta/examples/provider/ItemHandler.java in  processRequest (line 227) - it does returns CodecReturnCodes.FAILURE for the same scenario?

**Comment by fogol** [comment]
@umernalla Thank you for bringing this to our attention. We will investigate the issue. It will be fixed in further releases.

**Comment by vlevendel** [comment]
Addressed in RTSDK 2.2.2.L1. Closing.
