### ISSUE TITLE
Issues building VAConsumer on Linux (Pengwin Enterprise 8)

### ISSUE THREAD

**Issue by zinc1oxide** [Refinitiv/Real-Time-SDK#188]
I was able to find a related issue: https://github.com/Refinitiv/Real-Time-SDK/issues/107.

**Version**: RTSDK 2.0.3.L2

Working through the C/C++ installation guide, I followed the recommendations.  Specifically, to install lsb_release for Redhat.  I am able to build EMA examples, but having trouble building some ETA examples - specifically VAConsumer.  

**RedHat**:
> cat /etc/redhat-release
Rocky Linux release 8.4 (Green Obsidian)

This is what is happening:

> make VAConsumer
[ 62%] Built target librssl_tmp
[ 62%] Built target librssl
[ 87%] Built target librsslVA_tmp
[ 87%] Built target librsslVA
Consolidate compiler generated dependencies of target VAConsumer
make[3]: *** No rule to make target 'RTSDK-BinaryPack_rsslVACache_LIBRARY-NOTFOUND', needed by '/home/zinc1oxide/Real-Time-SDK/Cpp-C/Eta/Executables/ROC8_64_GCC850/Optimized/VAConsumer'.  Stop.
make[2]: *** [CMakeFiles/Makefile2:4495: Cpp-C/Eta/Applications/Examples/VAConsumer/CMakeFiles/VAConsumer.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:4502: Cpp-C/Eta/Applications/Examples/VAConsumer/CMakeFiles/VAConsumer.dir/rule] Error 2

Any suggestions?

**Comment by fogol** [comment]
@zinc1oxide 'RTSDK-BinaryPack_rsslVACache_LIBRARY-NOTFOUND' means your environment is specified as 'ROC8_64_GCC850' and there is a list of supported environments : 

OL7_64_GCC482
RHEL6_64_GCC444
RHEL8_64_GCC831
WIN_64_VS140
WIN_64_VS141
WIN_64_VS142

So we are providing RTSDK-BinaryPack_rsslVACache_LIBRARY only for those environments (OS + C/C++ compiler set). Unfortunately, using the environment 'ROC8_64_GCC850' you cannot link rsslVACache library and build examples that are using the library.

It is specified in the documentation, please look at ['Supported Platforms, OSs, Compilers'](https://github.com/Refinitiv/Real-Time-SDK/tree/master/Cpp-C#supported-platforms-oss-compilers).

I would suggest to try one of supported OSs.

**Comment by zinc1oxide** [comment]
Ok - thank you.
I am aware of the supported platforms but want to understand exactly where the limitations are.  For example, I can build the ETA _Consumer_ example - presumably because it only relies on **librssl**, which is a generated lib.  Some, like **librsslVACache**, **libdacs** appears to be the pre-built ones for the supported platforms and if applications attempt to reference those from an alternate OS, will fail - as I observed.

I do want to understand what this specific statement means "CMake build does attempt to normalize those dependencies to help with linking the pre-built libraries on other Linux platforms"?

**Comment by fogol** [comment]
@zinc1oxide Please, look at :

https://github.com/Refinitiv/Real-Time-SDK/blob/53a17f119a479f92b6ce3b4f7b500016ee0ea314/CMake/rcdevSystemInfo.cmake#L222

and 

https://github.com/Refinitiv/Real-Time-SDK/blob/53a17f119a479f92b6ce3b4f7b500016ee0ea314/CMake/rcdevSystemInfo.cmake#L247

and

https://github.com/Refinitiv/Real-Time-SDK/blob/53a17f119a479f92b6ce3b4f7b500016ee0ea314/CMake/rcdevSystemInfo.cmake#L270

'To normalize the dependencies' means to build the environment specification string like 'RHEL8_64_GCC831' and 'ROC8_64_GCC850' in your case.

**Comment by vlevendel** [comment]
There are two paths forward:  change CMake to normalize your build on an unsupported platform or copy the relevant libraries (Rocky Linux 8 can use RedHat 8 libs in this case) into a location where you can link against them. Closing.
