### ISSUE TITLE
RsslBuffer is not const-correct

### ISSUE THREAD

**Issue by dotfield** [Refinitiv/Real-Time-SDK#189]
It should be const char * not char *
The way you are throwing literals into it suggests it's unsafe to modify them anyway, so why is it not const char*?

If it's too late to change it then deprecate RsslBuffer and have an RsslConstBuffer or whatever.

(Actually I find it rather shocking that you ignore const-correctness in a library as important as this one).

**Comment by rongvietnj** [comment]
@dotfield  RsslBuffer is defined as struct below, not 'char *':

typedef struct
{
        rtrUInt32       length;         /*!< The length of the buffer. */
        char            *data;          /*!< The actual data buffer. */
} RwfBuffer;

typedef RwfBuffer RsslBuffer;

**Comment by rongvietnj** [comment]
Sorry, I had copy and paste error in previous comment.

See below for the definition of RsslBuffer.

```
typedef struct
{
        rtrUInt32       length;         /*!< The length of the buffer. */
        char            *data;          /*!< The actual data buffer. */
} RwfBuffer;

typedef RwfBuffer RsslBuffer;

```

**Comment by MitchellKato** [comment]
The Buffer's internal pointers can be changed or reassigned in several cases.  For example, the data pointer is reassigned when a buffer from rsslGetBuffer is packed with rsslPackBuffer.  In addition, we do change the buffer's position with internal buffers.
