### ISSUE TITLE
VAConsumer example web socket option does not work

### ISSUE THREAD

**Issue by andysCaplin** [Refinitiv/Real-Time-SDK#191]
I built the VAConsumer example using these [instructions](https://developers.refinitiv.com/en/article-catalog/article/deploy-and-run-elektron-sdk-docker).  
I have a client Id and credentials and I can use the application to connect via encryptedSocket to 
- eu-west-1-aws-3-sm.optimized-pricing-api.refinitiv.net:14002 
 
This works fine

But when I try to use encryptedWebSocket to connect to
- eu-west-1-aws-3-sm.optimized-pricing-api.refinitiv.net:443

I get this

```
Adding connection to eu-west-1-aws-3-sm.optimized-pricing-api.refinitiv.net:443...

Connection down, reconnecting.  Channel fd=-1
        Error text: <rwsReadResponseHandshake:1841> Invalid HTTP response, status code 400
```

Does this indicate that the library has an issue in creating the initial request ?
I've contacted Refinitiv re my credentials and I don't think this is a permissioning issue.

**Comment by MitchellKato** [comment]
It looks like the vaconsumer's default websocket protocols is incorrect for this connection.  It's an artifact of an older default, and we will look into fixing it in a future release. Can you please add the following to the vaconsumer's command line: 

-protocolList "tr_json2"

That will specify the json protocol and should allow you to connect.  By default, the API sets the websocket protocol as "tr_json2".

Mitchell

**Comment by andysCaplin** [comment]
Thanks. Now I can use encryptedWebSocket to connect to eu-west-1-aws-3-sm.optimized-pricing-api.refinitiv.net:443

But when I request MP:/VOD.L using that endpoint I get this error

```
Error Id: -1, Text: Failed to convert JSON message: {"ID":6,"Type":"Error","Text":"JSON Unexpected FID. Received 'PRE_10T156' for key 'Fields'","Debug":{"File":"/opt/refinitiv/Real-Time-SDK/Cpp-C/Eta/Impl/Converter/jsonToRwfSimple.C","Line":5116,"Offset":6255,"Message":"[{\"ID\":6,\"Type\":\"Refresh\",\"Key\":{\"Service\":\"ELEKTRON_DD\",\"Name\":\"/VOD.L\"},\"State\":{\"Stream\":\"Open\",\"Data\":\"Ok\"},\"Qos\":{\"Timeliness\":\"Realtime\",\"Rate\":\"JitConflated\"},\"PermData\":\"\u0003\u0001\u0001\uffffff92A\uffffffc0\u0007\u0000\",\"SeqNumber\":17535,\"Fields\":{\"PROD_PERM\":9241,\"RDNDISPLAY\":115,\"DSPLY_NAME\":\"VODAFONE GROUP/d\",\"RDN_EXCHID\":\"LSE\",\"TRDPRC_1\":122.79,\"TRDPRC_2\":123.46,\"TRDPRC_3\":123.46,\"TRDPRC_4\":123.46,\"TRDPRC_5\":123.78,\"NETCHNG_1\":-4.54,\"HIGH_1\":127.54,\"LOW_1\":121.98,\"PRCTCK_1\":\"\uffffffe2\uffffff87\uffffffa9\",\"CURRENCY\":\"GBp\",\"TRADE_DATE\":\"2022-03-04\",\"TRDTIM_1\":\"17:09:06\",\"OPEN_PRC\":126.92,\"HST_CLOSE\":128.00,\"BID\":121.56,\"ASK\":130.00,\"NEWS\":\"YYYY\",\"NEWS_TIME\":\"17:19:44\",\"BIDSIZE\":1000,\"ASKSIZE\":25000,\"ACVOL_1\":105442806,\"EARNINGS\":-0.5600,\"YIELD\":5.9297,\"PERATIO\":0.0000,\"DIVPAYDATE\":\"2022-02-04\",\"EXDIVD
```

Requesting MPO:/IBM.N using encryptedWebSocket  is fine.

**Comment by andysCaplin** [comment]
My application can now connect and login using encryptedWebSocket but before it gets the dictionaries it gets this error

```
2022/03/06-10:22:31.652409 +0000: (upasrc-load-0): NOTIFY: ETA Reactor: Connection reconnecting: Channel (0x7fea6c1436b0) fd=61 Error: (</home/build/workspace/Refinitiv-Poller-Build-EL6/Elektron-SDK/Cpp-C/Eta/Impl/Transport/rwsutils.c:3795> Error: 1007 Invalid Message Size. Message size is: (3304972). Max Message size is(614540)
)
```

I can't find any external way of increasing that max message size. I also can't see any obvious difference in the set up code between my app and VAConsumer. My app works fine if the connection type is encryptedSocket.

The main difference I can see is that I run the VAConsumer on an Oracle 7 docker and my app is running on CentOS 6.

**Comment by fogol** [comment]
Hi @andysCaplin : "Error: 1007 Invalid Message Size. Message size is: (3304972). Max Message size is(614540)" it's known issue, by design for now. It's because dictionary message size in JSON format higher then max message size that's designed in SDK.

Workaround is to use the dictionaries are supplied with SDK:

https://github.com/Refinitiv/Real-Time-SDK/tree/master/Cpp-C/etc

You need to copy these files to the working folder of your application example.

**Comment by andysCaplin** [comment]
Right - I hadn't noticed before that there are 2 dictionary files in the VAConsumer example directory
- RDMFieldDictionary
- RDMFieldDictionary_large

Are these all I need ?

Also, I assume it will be ok to ship these files with our product so that wss connections will work.

**Comment by jirapongse-refinitiv** [comment]
> Right - I hadn't noticed before that there are 2 dictionary files in the VAConsumer example directory
> 
> * RDMFieldDictionary
> * RDMFieldDictionary_large
> 
> Are these all I need ?
> 
> Also, I assume it will be ok to ship these files with our product so that wss connections will work.

RDMFieldDictionary and enumtype.def.

**Comment by andysCaplin** [comment]
Hi - thanks for the info.

This is only an issue for JSON. 
- So that means that if my endpoint is providing rwf then I should still get the dictionaries from the provider since that is the most up to date info.
- And I should only load from these files if the provider is JSON.
Is that correct ?

Is this something that will get fixed in a future release ?

Also - has the /VOD.L issue I mentioned earlier been fixed ?

**Comment by fogol** [comment]
@andysCaplin 
> This is only an issue for JSON.
> 
>     * So that means that if my endpoint is providing rwf then I should still get the dictionaries from the provider since that is the most up to date info.
> 
>     * And I should only load from these files if the provider is JSON.
>       Is that correct ?

That is correct.

> Is this something that will get fixed in a future release ?

We are working on it. You might to choose RWF protocol instead of JSON for your application. It is an official recomentation for now.

> Also - has the /VOD.L issue I mentioned earlier been fixed ?

We will investigate it as a separate issue.

**Comment by andysCaplin** [comment]
Just FYI - the same JSON/RWF issue happens with pages

```
2022/03/13-17:21:51.609732 +0000: (TREPAdap-load-0): ERROR: ETA Reactor: Error Id: -1, Text: Failed to convert JSON message: {"ID":5,"Type":"Error","Text":"JSON Unexpected FID. Received 'PRE_16T032' for key 'Fields'","Debug":{"File":"/home/build/workspace/Refinitiv-Poller-Build-EL6/Elektron-SDK/Cpp-C/Eta/Impl/Converter/jsonToRwfSimple.C","Line":5116,"Offset":2703,"Message":"[{\"ID\":5,\"Type\":\"Refresh\",\"Key\":{\"Service\":\"ELEKTRON_DD\",\"Name\":\"SPEED/GUIDE1\"},\"State\":{\"Stream\":\"Open\",\"Data\":\"Ok\"},\"Qos\":{\"Timeliness\":\"Realtime\",\"Rate\":\"JitConflated\"},\"PermData\":\"\u0003\u0001\u00012E\uffffffc0\u0017\u0000\",\"SeqNumber\":79,\"Fields\":{\"PROD_PERM\":3245,\"RDNDISPLAY\":151,\"RECORDTYPE\":226,\"ROW80_1\":\"WELCOME TO THE SPEED GUIDE TO REFINITIV INFORMATION                 SPEED/GUIDE1\",\"ROW80_2\":\"Welcome to REFINITIV Speed Guide pages. Speed Guides are a navigational tool    \",\"ROW80_3\":\"for finding your way around the REFINITIV database.                             \",\"ROW80_4\":\"                                                                                \",\"ROW80_5\":\"=EXPLANATION====================================================================\",\"ROW80_6\":\"With the exception of the top level market pages (BONDS, BROKE
```

**Comment by vlevendel** [comment]
We have conveyed the issue to RTO team who have this prioritized for a subsequent release.

In general, please note that you may reach out for support via [Development Portal](https://developers.refinitiv.com/) (if you have premium support) or [Product Support](https://my.refinitiv.com/content/mytr/en/helpandsupport.html).
