### ISSUE TITLE
Port binding does not seem released after OMMProvider exists scope (Linux only)

### ISSUE THREAD

**Issue by zfarberov** [Refinitiv/Real-Time-SDK#192]
Hello @Real-Time-SDK team,

I am following up on client report on dev forums:
https://community.developers.refinitiv.com/questions/91318/port-not-closed-after-destroying-ommprovider.html

Having tested this on windows RTSDK first, and not found the issue as described, I have consequently re-tested on Linux Oracle 7.4, RTSDK versions 2.0.0 and 2.0.4, I am seeing/reproducing the non-release with both versions.

Can use the code supplied by the client to reproduce (please find in dev forums question) or just introducing loop into IProv100 example (attached) and run example Consumer100 against it (unmodified) and exit:
[IProvider.zip](https://github.com/Refinitiv/Real-Time-SDK/files/8238307/IProvider.zip) see "Unable to bind socket" on provider at the next iteration of the loop:

"root@45684e27c875 Optimized]# ./IProv100

Iteration: 0 coming in...
Exception Type='OmmInvalidUsageException', Text='Attempt to submit UpdateMsg with non existent Handle = 139779509414192.', ErrorCode='-22'

Iteration: 0 coming out...

Iteration: 1 coming in...
Exception Type='OmmInvalidUsageException', Text='Failed to initialize OmmServerBaseImpl (Unable to bind RSSL server).' Error Id='-1' Internal sysError='98' Error Location='' Error Text='</opt/refinitiv/Real-Time-SDK/Cpp-C/Eta/Impl/Transport/ripcutils.c:1248> Error: 1002 *Unable to bind socket*. System errno: (98)
'. ', ErrorCode='-1'

"

Is there perhaps an additional cleanup step, that needs to be handled by IProvider app on Linux?
Let me know what you think? 
Thanks, 
-Zoya

**Comment by fogol** [comment]
@zfarberov Thank you for bringing this to our attention. It will be fixed in further releases.

**Comment by vlevendel** [comment]
Addressed with release 2.0.6.L1.  Please reopen if there are additional issues.
