### ISSUE TITLE
A version of Windows libcurl.dll needed that can connect to a HTTPS proxy

### ISSUE THREAD

**Issue by msingh-fs** [Refinitiv/Real-Time-SDK#193]
Using the RTSDK C/C++ (version 2.0.3.L2) runtime DLLs on Windows 10, we get the error:

Error: Failed to perform the request with text: A requested feature, protocol or option was not found built-in in this libcurl due to a build-time decision.

when trying to go through a HTTPS proxy

Refinitiv have stated that the Windows build of libcurl has the build option using schannel so a connection to a HTTPS proxy will not work. They have suggested the option should be switched to use OpenSSL

Can we request that Refinitiv add this feature to the SDK so that we get a libcurl DLL that can go through either a HTTP or HTTPS proxy

NOTE: We are using the supplied libraries and DLLs. We are not building the RTSDK from source

**Comment by vlevendel** [comment]
Closing as this turned out to be proxy issue.
