### ISSUE TITLE
InitailizationTimeout is 0 sec

### ISSUE THREAD

**Issue by thilinak** [Refinitiv/Real-Time-SDK#196]
Please refer: https://community.developers.refinitiv.com/questions/92519/initailizationtimeout-is-0-sec.html

**Comment by fogol** [comment]
@thilinak Thank you for bringing this to our attention. We will investigate the issue. It will be fixed in further releases.

**Comment by thilinak** [comment]
Thanks. Please keep me updated.

**Comment by owenmmccrady** [comment]
Is there an update on this issue please?

**Comment by fogol** [comment]
@owenmmccrady We are working on it. It will be fixed in further releases.

**Comment by vlevendel** [comment]
Addressed with release 2.0.6.L1. Please reopen if there are additional issues.

**Comment by thilinak** [comment]
Noted. Thanks
