### ISSUE TITLE
please deploy Java EMA test jar to MavenCentral

### ISSUE THREAD

**Issue by dlipofsky** [Refinitiv/Real-Time-SDK#197]
The main EMA JAR (`com.refinitiv.ema:ema`) is published to MavenCentral (`search.maven.org`) but the test classes are not.
Many projects will publish a `*-test.jar` (separate from the main JAR) that has the test classes.
Can you please do that?

I am interested in classes like `Java/Ema/Core/src/test/java/com/refinitiv/ema/unittest/TestUtilities.java` (and probably the rest of `Ema/Core/src/test`) as these are often referred to in the developer forum as possible solutions to the unit tests, but they are not available unless you build them yourself - and the build is setup with gradle, and I don't know gradle. I've been trying all day to build it myself and I don't feel close yet.

**Comment by fogol** [comment]
@dlipofsky You can use our instructions how to build and run examples of RTSDK with Gradle:

[Building RTSDK Using Gradle](https://github.com/Refinitiv/Real-Time-SDK/tree/master/Java#building-rtsdk)

To run EMAJ Unit Tests you need to run a command:

`./gradlew Ema:Core:test`

Or its equivalent for Windows.

To run a specific test or bunch of tests you need to use an option:

`./gradlew Ema:Core:test --tests *EmaFileConfigJunitTests*`

Where \*EmaFileConfigJunitTests\* is a template, as an example to run all tests of

`public class EmaFileConfigJunitTests`

You can find it here:

https://github.com/Refinitiv/Real-Time-SDK/blob/05cc073af32ddb28ceb10bcd05a375e0434830af/Java/Ema/Core/src/test/java/com/refinitiv/ema/access/EmaFileConfigJunitTests.java#L23

And you can point to the one single specific test to run, like:

`./gradlew Ema:Core:test --tests EmaFileConfigJunitTests.testLoadCfgFromFile`

It would run exactly the case public void testLoadCfgFromFile() :

https://github.com/Refinitiv/Real-Time-SDK/blob/05cc073af32ddb28ceb10bcd05a375e0434830af/Java/Ema/Core/src/test/java/com/refinitiv/ema/access/EmaFileConfigJunitTests.java#L40

**Comment by dlipofsky** [comment]
@fogol I am not trying to run the tests, I am trying to make the test code available as a JAR to my project so that I can create unit tests in my project. The problem as it stands now is I can create objects in my code using `EmaFactory` or `JUnitTestConnect` but they don't work because I get
"_Decoding of just encoded object in the same application is not supported_" or `NullPointerException`.  From what I can tell from discussions in the developer forums ( [here](https://community.developers.refinitiv.com/questions/92982/creating-fieldentry-for-unit-tests.html), [here](https://community.developers.refinitiv.com/questions/84689/how-to-decode-refreshmsg-for-unittesting-purposes.html), and [here](https://community.developers.refinitiv.com/questions/6594/what-is-the-preferred-way-to-unit-test-decoding-of.html) ) you must do some extra steps to prepare the object, and there is really no way to do this with the existing published code, and the code in the test package might work, but it is not published.

**Comment by fogol** [comment]
@dlipofsky We have internal unit tests that cover encoding and decoding that are package private. We can certainly improve these if you find there are gaps. Also please feel free to add to our unit tests with a pull request (please fill in the sdk agreement).

[Contributing](https://github.com/Refinitiv/Real-Time-SDK/tree/master/Java#contributing)

**Comment by dlipofsky** [comment]
@fogol, I am interested in testing my code, not your code.

**Comment by fogol** [comment]
@dlipofsky All EMA Java unit tests is open-sourced. It is published here.

Would you mind to share your case of code sample?

**Comment by dlipofsky** [comment]
@fogol the code is here, but I would have to create the JAR myself (I have no gradle experience, and spent about a day trying without success) and then deploy it to my own maven repo. It would be much better if there was a test JAR with utilities to do this published to Maven Central.

My code would create a list of `FieldEntry` and set it as a payload of a `RefreshMsg` and then pass it to my implementation of `OmmConsumerClient` and check the results to confirm my implementation correctly converted the data. You can see my attempt at the first step in the [developer forum](https://community.developers.refinitiv.com/questions/92982/creating-fieldentry-for-unit-tests.html) but it fails because "Decoding of just encoded object in the same application is not supported".

**Comment by vlevendel** [comment]
@dlipofsky We don't permit decoding of a just encoded object for efficiency reasons - this is per design. As you've noted, TestUtilities are open source and available for use. At this juncture we do not have a plan to make a -test.jar available. We will take this into consideration if there is more demand. Closing this issue.

**Comment by dlipofsky** [comment]
@vlevendel  How does efficiency play into this? I am not asking you to change the main code, just to provide test code. As I noted building the test JAR is difficult - as I noted I'm an experienced developer and spent a whole day trying and failed.

**Comment by vlevendel** [comment]
@dlipofsky We'll go ahead and create a test jar for you in our next quarter release. You just need TestUtilities, correct?
