### ISSUE TITLE
Service Discovery curl issue

### ISSUE THREAD

**Issue by andysCaplin** [Refinitiv/Real-Time-SDK#199]
The RTO service Discovery feature won't work out of the box when the RT SDK is linked to an application that is itself linked to OpenSSL 1.1. This is because the curl library provided by RT SDK uses OpenSSL 1.0.

This should be documented to save users some time.

I got around this by creating my own curl library linked to the same version of OpenSSL 1.1 that my application is linked to.

The progress of the issue is shown here - [VAConsumer application curl issue - Forum | Refinitiv Developer Community](https://community.developers.refinitiv.com/questions/90815/vaconsumer-application-curl-issue.html)

**Comment by fogol** [comment]
@andysCaplin Thank you for bringing this to our attention. The documentation will be updated in further releases.

**Comment by vlevendel** [comment]
[Documented ](https://github.com/Refinitiv/Real-Time-SDK/tree/master/Cpp-C#external-dependencies)with tag Real-Time-SDK-2.0.7.L1

**Comment by andysCaplin** [comment]
Thanks for this. I was thinking - if there is a FAQ for issues with creating an RTO application this could be added as a potential issue if the application reports issues with curl.
