### ISSUE TITLE
Recovery from a force logout

### ISSUE THREAD

**Issue by simon-dando-chelmer** [Refinitiv/Real-Time-SDK#200]
Hi,
We need to remain connected across your maintenance windows, and have noticed that we occasionally get this message usually across the weekend: 

Status msg received: StatusMsg
    streamId="1"
    domain="Login Domain"
    state="Closed / Suspect / Not entitled / 'Force Logout from DACS.'"
    name="<snip>"
    nameType="1"
StatusMsgEnd

Then we would continuously get the following until we restarted our service:
java.lang.NullPointerException: null
	at com.refinitiv.ema.access.SingleItem.rsslSubmit(ItemCallbackClient.java:2999)
	at com.refinitiv.ema.access.SingleItem.open(ItemCallbackClient.java:2861)
	at com.refinitiv.ema.access.ItemCallbackClient.registerClient(ItemCallbackClient.java:2184)
	at com.refinitiv.ema.access.OmmBaseImpl.registerClient(OmmBaseImpl.java:468)
	at com.refinitiv.ema.access.OmmConsumerImpl.registerClient(OmmConsumerImpl.java:142)

We were advised by your support team to listen for the force logout and then recreate the OmmConsumerImpl but that just causes this problem when we try to register a new listener until we restart our service. 
2022-06-19 10:01:09,210 [pool-11-thread-1] INFO  c.c.m.r.RefinitivOmmConsumerClient - Status message received: StatusMsg
    streamId="6"
    domain="MarketPrice Domain"
    state="Open / Suspect / None / 'Service not available'"
    name="OZY.NZ"
    serviceName="ELEKTRON_DD"
StatusMsgEnd

I feel that this would be best resolved in your ema/eta libraries to save each client jumping through hoops. In the meantime, please advise how we might best handle this, rather than having a cron to restart our service at the end of your weekend maintenance window. I understand we are still exposed to this risk during maintenance windows during the week and also don't want to add a daily cron to restart (we have long running overnight jobs looking at global market data, from a local instance).

Thanks

**Comment by fogol** [comment]
@simon-dando-chelmer Thank you for bringing this to our attention. We will investigate the issue.

**Comment by simon-dando-chelmer** [comment]
Hi @vlevendel. 
"Regarding NullPointerExceptions: Is it really never-ending NPEs or exactly as many NPEs as your watchlist size?" > They are never-ending NPE's, presumably because we are attempting to subscribe with an invalid ommConsumer. They have not been seen since service desk advised to recreate the ommConsumer.

"your application will be recreating OmmConsumer in response during that period (please confirm that this is happening)" > we are trying to do this, but do not always since the errors / status msgs coming back from the api have been changing. It is a protracted issue since we only see the problem once every 3 weeks give or take.

Regarding it being 'ease of use', I would tend to agree except for reconnecting during a maintenance window. This has been an outstanding issue for us for about 6 months. Ideally your library would take care of this without input from the customer.

**Comment by vlevendel** [comment]
@simon-dando-chelmer  It's good to know that NPEs are not an issue. 

Regarding " since the errors / status msgs coming back from the api have been changing", what are the specific status messages that are changing?  What is the issue you'd like for us to address?

To keeps things simple at this layer, the recommendation stands that you must recreate the OmmConsumer.  As mentioned Open/Suspect status messages are standard when the consumer is attempting to reconnect (if your reconnect parameters are set to default, the API will recover all the items once the maintenance window is complete).  Once maintenance window is complete, you will get Open/Ok messages. Please let us know if this not occuring.

**Comment by simon-dando-chelmer** [comment]
@vlevendel - I've already engaged another team about being able to reconnect after a maintenance window but I am reporting it here, so you would consider encapsulating the ability to automatically reconnect after a maintenance window behind your api, to make it easier for other users. We are only impacted once every few weeks so it has been pretty painful trying to get this resolved. I guess most users though don't have their process running 24/7.

**Comment by vlevendel** [comment]
API does automatically reconnect from non-final states. Is there a problem with recovery post maintenance window and after recreating the OmmConsumer? If so, please provide logs so we can investigate.

**Comment by simon-dando-chelmer** [comment]
Right, but way back I had been originally hoping it could be fully encapsulated without even needing to recreate the OmmConsumer, given even doing that didn't work as advised. We are still in the process of waiting to test our latest change, and then we sometimes have to wait a few weeks for the problem to be seen again. Thanks, we will send more information if we find we still have problems.

**Comment by vlevendel** [comment]
Thank you. Please feel free to reopen with more information. Closing for now.

**Comment by simon-dando-chelmer** [comment]
Hi @vlevendel . fyi updating with more information. The weekend before last, we started recovering ok, until we saw a status message that we hadn't seen before. So we just added that message to the list of status messages that will invoke an OmmConsumer recreation. However this weekend we kept recreating for about 4 minutes until we copped a fatal
2022-08-28 02:09:10,604 [pool-8-thread-1] ERROR c.c.m.r.RefinitivRealtimeServiceImpl - Failed to init OMM consumer due to login failed (timed out after waiting 45000 milliseconds) for :) [ http://tkp.to/hjCsiTKFkQ ]
com.refinitiv.ema.access.OmmInvalidUsageExceptionImpl: login failed (timed out after waiting 45000 milliseconds) for :)
	at com.refinitiv.ema.access.OmmBaseImpl.ommIUExcept(OmmBaseImpl.java:1603)
	at com.refinitiv.ema.access.OmmBaseImpl.handleLoginReqTimeout(OmmBaseImpl.java:1414)
	at com.refinitiv.ema.access.OmmConsumerImpl.handleAdminDomains(OmmConsumerImpl.java:492)
	at com.refinitiv.ema.access.OmmBaseImpl.initialize(OmmBaseImpl.java:277)
	at com.refinitiv.ema.access.OmmConsumerImpl.<init>(OmmConsumerImpl.java:42)
	at com.refinitiv.ema.access.EmaFactory.createOmmConsumer(EmaFactory.java:237)
	at com.chelmer.mds.refinitiv.RefinitivRealtimeServiceImpl.setNewOmmConsumer(RefinitivRealtimeServiceImpl.java:94)

So if we encounter this we will retry with a decaying delay.

**Comment by simon-dando-chelmer** [comment]
@vlevendel do you happen to know if a force logout is expected to occur at the beginning or end of an upgrade? I assume the beginning assuming you don't switch users across to another server(s) until the upgrade is complete.

**Comment by vlevendel** [comment]
@simon-dando-chelmer A "Force Logout" can occur at the beginning of the maintenance window due to the user/token no longer being valid.  During a maintenance window as backend components are restarted/rebuilt, it is possible for the user to be temporarily invalid causing a forced disconnect.

Once disconnected, the API will attempt to automatically reconnect. After channel is established, login request is sent out but is not met with a login response from the server since server side is undergoing maintenance. This will results in the 45000 millisecond timeout stack you see above.  Your reaction to retry with delay is appropriate.
