### ISSUE TITLE
EMA Java WebSocket connection is unable to download multiple part dictionary from ADS.

### ISSUE THREAD

**Issue by jirapongse-refinitiv** [Refinitiv/Real-Time-SDK#203]
ADS 3.4.0 introduced the enableMultipartDictionary configuration to send dictionary with multiple part refresh messages.

```
*ads*enableMultipartDictionary : True
```

I tested it on EMA C++ and EMA Java with the WebSocket connection type. EMA will download the dictionary from ADS.

EMA C++ with the WebSocket connection type works fine while EMA Java 3.6.6.L1 reported the following error.

```
Jul 22, 2022 10:58:45 AM com.refinitiv.ema.access.ChannelDictionary processCallback
WARNING: loggerMsg
    ClientName: ChannelDictionary
    Severity: Warning
    Text:    RDMDictionary stream was closed with status message
	streamId 4
	Reason State: Closed/Suspect/None - text: "Login stream was closed."
loggerMsgEnd


Failed to convert JSON message: JSON Converter parse error: Invalid UTF-8 middle byte 0x22
 at [Source: (com.refinitiv.eta.json.converter.ByteBufferInputStream); line: 1, column: 3187]
```

**Comment by fogol** [comment]
@jirapongse-refinitiv Thank you for bringing this to our attention. We will investigate the issue. This issue will be fixed in further releases.
