### ISSUE TITLE
ChannelSet Programmatic Configuration in EMA Configuration document

### ISSUE THREAD

**Issue by wasin-waeosri** [Refinitiv/Real-Time-SDK#204]
The EMA API ChannelSet programmatic configuration in section "4.5.3 Example: Programmatic Configuration of the Consumer" of the EMA Java Configuration guide document (EMAJ_ConfigGuide.pdf) missing the innerElementList.clear() statement between two channels set up.

Code from the document:
![image](https://user-images.githubusercontent.com/27797359/182354329-34abdc27-eb17-44d7-a34e-df662df27140.png)

I have tried the code above and the API always set Channel_1 and Channel_2 to the same Host and Port. 

The correct code should have the _innerElementList.clear()_ statement between 2 channels set up as follows:

`
innerElementList.add(EmaFactory.createElementEntry().ascii("ChannelType", "ChannelType::RSSL_SOCKET"));
innerElementList.add(EmaFactory.createElementEntry().ascii("Host", "localhost"));
innerElementList.add(EmaFactory.createElementEntry().ascii("Port", "14002"));
innerMap.add(EmaFactory.createMapEntry().keyAscii( "Channel_1", MapEntry.MapAction.ADD, innerElementList));

innerElementList.clear() //<-- This one 

innerElementList.add(EmaFactory.createElementEntry().ascii("ChannelType", "ChannelType::RSSL_SOCKET"));
innerElementList.add(EmaFactory.createElementEntry().ascii("Host", "121.1.1.100"));
innerElementList.add(EmaFactory.createElementEntry().ascii("Port", "14008"));
innerMap.add(EmaFactory.createMapEntry().keyAscii( "Channel_2", MapEntry.MapAction.ADD, innerElementList));
innerElementList.clear()
`
The EMA C/C++ Configuration guide document (EMACPP_ConfigGuide.pdf) does not have this issue because the example uses a single channel.

**Comment by vlevendel** [comment]
@wasin-waeosri Thank you for bringing this to our attention. We will investigate and address it in a future release.

**Comment by vlevendel** [comment]
EMAJ ConfigGuide has been fixed with tag Real-Time-SDK-2.0.7.L1
