### ISSUE TITLE
EMA Library Timeout Issues

### ISSUE THREAD

**Issue by habibLSEG** [Refinitiv/Real-Time-SDK#209]
A client application written with EMA sends batch request of multiple instruments to the RTMDS elektron feed ... and in return , some of the requests return status of closed/suspect/timeout :

2022-09-02 13:30:41,302 [main] WARN : Request failed: service=IDN_RDF name=AG1G.DE Response= ResponseCode=Status StatusCode=None description=Open / Suspect / None / 'Request timeout'

Please see the attached file with stdout log of EMA and the ADS responses. 

We are unable to re-produce this issue internally within Lseg. We need some guidance on what's causing this issue and how to fix it.
[stdout.log](https://github.com/Refinitiv/Real-Time-SDK/files/9648939/stdout.log)

**Comment by L-Karchevska** [comment]
@habibLSEG  Thank you for bringing this to our attention, we will investigate this issue.

**Comment by L-Karchevska** [comment]
@habibLSEG 

The error that you are describing   

> WARN : Request failed: service=IDN_RDF name=AG1G.DE Response= ResponseCode=Status StatusCode=None description=Open / Suspect / None / 'Request timeout'

can occur upon item request timeout when the application does not receive a response to its request for a preconfigured period of time. The default value for the request timeout is 15 seconds (please refer to EMAJ ConfigGuide documentation, section 3.1.4).

Question: Does the problem happen if items that get this status are requested outside of the batch request?

Question: Is it consistently the same items?

Question: If re-requested by application upon getting a status, does the application receive a response?

NOTE: The attached log shows a different status message for item name of "NODATA": "*The record could not be found" dataSize="0" and has no examples of Request timeout Status messages.

**Comment by habibLSEG** [comment]
@L-Karchevska ... after some further testing, the EMA dev team was able to reproduce the issue (Pimchaya Wongkurun & team) , and we were advised to make some code modifications as well as upgrade to EMA 3.6.7.1. The internal tests so far look promising , we are not in UAT with the client....will update further after client's feedback.
