### ISSUE TITLE
Consumer does not release objects when it is unable to connect in EMA Java

### ISSUE THREAD

**Issue by ardyesp** [Refinitiv/Real-Time-SDK#210]
A client reported this issue where repeatedly trying to create an OMMConsumer which does not connect, results in heap memory increase and eventual failure. I can verify it with following snippet of code:

```
while(consumer == null)	{
  try {
    consumer  = EmaFactory.createOmmConsumer( config.host(hostStr).username(userStr) );
  }
  catch(Throwable e)	{
    System.out.println("Consumer is null");
  }
}
```
Result after running for two hours, some of the objects aren't getting GC'd:
![heap](https://user-images.githubusercontent.com/12713441/194407861-9a8e5ba9-40ad-415a-80a6-edd753851d29.png)

**Comment by L-Karchevska** [comment]
@ardyesp Thank you for bringing up this issue and presenting steps for reproduction, we will investigate it. Could you also provide the hostStr and userStr values that you are using?

**Comment by ardyesp** [comment]
Hi @L-Karchevska,
These parameters are irrelevant, but here they are:

hostStr = localhost
userStr = radmin

**Comment by ardyesp** [comment]
I have tried the issue with RTSDK 2.7.0.L1 and don't see it anymore. Objects are getting GC'd properly now.

![image](https://user-images.githubusercontent.com/12713441/195168125-e4270492-7520-4274-a3f0-01c9f54ff561.png)
