### ISSUE TITLE
Undocumented field "ReactorEventFdPort"

### ISSUE THREAD

**Issue by mattgodbolt** [Refinitiv/Real-Time-SDK#214]
The programmatic configuration examples refer to `ReactorEventFdPort` in the consumer, which is not documented. The example in the configuration documentation also specifies this parameter, but it makes no other mention of it.

**Comment by L-Karchevska** [comment]
@mattgodbolt Thank you for reporting this issue! We will look into it and apply changes where necessary.

**Comment by dmykhailishen** [comment]
@mattgodbolt, thank you for reporting this issue. This parameter is no longer used. We will clean up it in the code and in the documentation.

**Comment by vlevendel** [comment]
Fixed with tag Real-Time-SDK-2.0.8.L1.
