### ISSUE TITLE
Erroneous documentation for Logger

### ISSUE THREAD

**Issue by mattgodbolt** [Refinitiv/Real-Time-SDK#215]
In Logger Group documentation in the CPP Config Guide, it suggests that the parameter names `RdmFieldDictionaryFileName` and `EnumTypeDefFileName` are valid keys for the `<Logger>`, which seems incorrect (I can find no reference in the code to this)

**Comment by L-Karchevska** [comment]
@mattgodbolt Thank you for reporting the issue! Could you point to the exact location where you've seen this problem? I checked the CPP Config Guide and the EMA examples, it looks like RdmFieldDictionaryFileName and EnumTypeDefFileName are not used as keys for the <Logger> entry, instead, these are the valid keys for <Dictionary> entry.

**Comment by vlevendel** [comment]
Fixed with tag Real-Time-SDK-2.0.8.L1
