### ISSUE TITLE
Request: Logger mode redirecting to stderr

### ISSUE THREAD

**Issue by mattgodbolt** [Refinitiv/Real-Time-SDK#216]
We can only choose a filename (which will always be postfixed with a `_pid` or a `_num`), or `stdout` as a log destination. For many linux applications, `stderr` is an appropriate output destination.

**Comment by L-Karchevska** [comment]
@mattgodbolt Thank you for reporting this request, we've created an internal JIRA to look into it.

**Comment by vlevendel** [comment]
@mattgodbolt Please feel free to redirect stdout (our default) to stderr if that's what you'd like to use as a log destination. Please reopen if you have further concerns.

**Comment by mattgodbolt** [comment]
Hi @vlevendel - In my example I can't redirect stdout to stderr - we communicate other information on stdout, and use stderr for logging (like most UNIX processes; we can then use pipes etc to write query tools without the log information getting in the way of the actual results).

**Comment by mattgodbolt** [comment]
Right now; my workaround is to redirect a file; but I can't even specify a single filename to redirect to (as the filename I give is always modified in some way, be it to add the PID or a file index). So I can't log (e.g.) to `/dev/fd/2`  or to a pipe or similar.

**Comment by vlevendel** [comment]
@mattgodbolt We'll consider an enhancement to send the log to stderr for a future release.

**Comment by vlevendel** [comment]
This is included with tag, Real-Time-SDK-2.1.3.L1. Please let us know if you have further questions.
