### ISSUE TITLE
Deadlock with OmmConsumer

### ISSUE THREAD

**Issue by charanyarajagopalan** [Refinitiv/Real-Time-SDK#218]
To give some background, we are creating an EMA consumer, and then opening item streams (100 items batched in each ReqMsg) with the consumer. We simply stop seeing new messages a few minutes after the consumer is established, without any exceptions or errors. This happens while the loop of opening item streams is ongoing. Debugging shows that there is potentially a deadlock situation occurring, as illustrated by the stack traces below. Is there some kind of rate/limit as to how batched requests should be created (we have a single Machine ID and hence a single EMA consumer). Version used is 3.6.7.1

![image](https://user-images.githubusercontent.com/11029452/200457048-8bd8c044-2ec1-4988-a406-eada75b5301b.png)
[deadlock-trace.txt](https://github.com/Refinitiv/Real-Time-SDK/files/9985773/deadlock-trace.txt)

**Comment by charanyarajagopalan** [comment]
Update: I increased the batch size to 5000, which means our item list gets through in 3 batched requests, I am still running into the same issue, though not every single time.

**Comment by dmykhailishen** [comment]
@charanyarajagopalan, Thank you for reporting this issue. We will investigate it and fix it in future releases.

**Comment by charanyarajagopalan** [comment]
Update: Switched to using the USER_DISPATCH operational model instead of API_DISPATCH. This helps control preventing message dispatch from being triggered during the creation of the item streams, and prevents deadlock from happening.

**Comment by L-Karchevska** [comment]
@charanyarajagopalan Thank you for additional details! 
The stack traces indeed indicate a potential deadlock. The USER_DISPATCH mode eliminates the issue because it makes both requests sending and callbacks be executed on the same thread. However, as for now, we were not able to reproduce the deadlock in our environment. Could you send a code example that reproduces the issue?

**Comment by charanyarajagopalan** [comment]
@L-Karchevska thanks, https://github.com/charanyarajagopalan/issue-218-repro
Will need credentials updated into application.yml to run.

**Comment by vlevendel** [comment]
@charanyarajagopalan  This is addressed with tag Real-Time-SDK-2.0.8.L1.  Please let us know if there are further concerns.
