### ISSUE TITLE
Snapshot requests to IProvider

### ISSUE THREAD

**Issue by Daniela-O** [Refinitiv/Real-Time-SDK#221]
To give you some background, we are migrating a Java application IProvider from RFA to EMA.

When testing the old RFA IProvider application with a Consumer application, the provider application was able to distinguish between snapshot and streaming requests sent by the consumer. I.e. in case of a snapshot request the Java class implementing the Client interface inside the Provider application received an OMMSolicitedItemEvent with MsgType OMMMsg.MsgType.NONSTREAMING_REQ.

When testing the same with an Ema IProvider application the EMA Java reqMsg.interestAfterRefresh() statement on the IProvider side always returns true even when it receives a request message with .interestAfterRefresh(false) setting from the Consumer side.
Thus there is no way to distinguish if Consumer is asking for a Snapshot or a Streaming and thus if IProvider has to reply with only a Refresh or also with Updates.

For test we used ex102_MP_Snapshot example for consumer and ex100_MP_Streaming/ex102_MP_Snapshot examples for providers.

We used Ema version 3.6.6.0 (but the same has been reproduces also with 3.6.7.0 L2), while RFA version was 8.0.1.E3

**Comment by wasin-waeosri** [comment]
Hi Team,

I just want to add more information about this API behavior. I can replicate the issue with EMA Java 3.6.7.0 L2 using the  EMA Java consumer example ex102_MP_Snapshot connects to the IProvider ex102_MP_Snapshot example.

The Provider ex102_MP_Snapshot is modified to print out the incoming ReqMsg object as follows:

`void processMarketPriceRequest(ReqMsg reqMsg, OmmProviderEvent event){
	System.out.println("DEBUG: processMarketPriceRequest");
	System.out.println(reqMsg);
	System.out.println("DEBUG: processMarketPriceRequest: ReqMsg.interestAfterRefresh()");
	System.out.println(reqMsg.interestAfterRefresh());
		
	...
	event.provider().submit(...);
}`

The running result is as follows:
`
DEBUG: processMarketPriceRequest
ReqMsg
    streamId="3"
    domain="MarketPrice Domain"
    name="EUR="
    serviceId="1"
    serviceName="DIRECT_FEED"
ReqMsgEnd

DEBUG: processMarketPriceRequest: ReqMsg.interestAfterRefresh()
true
`
The XML Trace message shows that the API receives a snapshot request from the consumer:
`

<REQUEST domainType="MARKET_PRICE" streamId="3" containerType="NO_DATA" flags="0x42 (HAS_PRIORITY|HAS_QOS)" Qos: Realtime/TickByTick/Static - timeInfo: 0 - rateInfo: 0 priorityClass="1" priorityCount="1" dataSize="0">
    <key flags="0x03 (HAS_SERVICE_ID|HAS_NAME)" serviceId="1" name="EUR="/>
    <dataBody>
    </dataBody>
</REQUEST>
`

**Comment by L-Karchevska** [comment]
@Daniela-O @wasin-waeosri Thank you for reporting this issue and additional details! We were able to reproduce the steps that you've mentioned and created an internal JIRA to investigate and fix this issue.

**Comment by wasin-waeosri** [comment]
Hi team,

Do you have any ETA or updates about the fix? There is [another client](https://community.developers.refinitiv.com/questions/102703/interestafterrefresh-always-returning-true-even-fo.html) who encounters the same issue on the Q&A forum.

**Comment by vlevendel** [comment]
Fixed with tag, Real-Time-SDK-2.1.0.L1.  Please let us know if you have further questions or concerns.
