### ISSUE TITLE
How to do integration of Elektron service with java application

### ISSUE THREAD

**Issue by maharanaprathapsing** [Refinitiv/Real-Time-SDK#222]
Hi Team,

I am beginner to the Elektron EMA. I have to integrate one of our spring boot application with ERT. I need some guidance on how to achieve this.

For now, I have taken Consumer.java (450-series) from examples and then added java file in our spring boot application. This is how i have integrated with ERT. I am able to get the data from ERT service. Is this correct approach? or Any other standard procedure that do I need to follow?

Any confluence on Java integration or any documentation is much appreciated. Thanks

**Comment by L-Karchevska** [comment]
@maharanaprathapsing Thank you for your question! The EMA examples are intended for demonstration purposes and as such show the general approach to using certain functionality, so you may have to change the examples code to achieve necessary results. For a detailed description of what each example does, please refer to the respective ReadMe file corresponding to each example. The detailed description of EMA library functionality can be found in EMA documentation files: https://github.com/Refinitiv/Real-Time-SDK/tree/master/Java/Ema/Docs. The documentation for the underlying ETA layer can be found in https://github.com/Refinitiv/Real-Time-SDK/tree/master/Java/Eta/Docs.

**Comment by umernalla** [comment]
@maharanaprathapsing - for additional input and guidance, you could also use the Developer forum to discuss your requirements and you may get some useful input - https://community.developers.refinitiv.com/spaces/71/index.html

**Comment by vlevendel** [comment]
> > @maharanaprathapsing Thank you for your question! The EMA examples are intended for demonstration purposes and as such show the general approach to using certain functionality, so you may have to change the examples code to achieve necessary results. For a detailed description of what each example does, please refer to the respective ReadMe file corresponding to each example. The detailed description of EMA library functionality can be found in EMA documentation files: https://github.com/Refinitiv/Real-Time-SDK/tree/master/Java/Ema/Docs. The documentation for the underlying ETA layer can be found in https://github.com/Refinitiv/Real-Time-SDK/tree/master/Java/Eta/Docs.
> 
> @L-Karchevska , Thanks for the inputs. Yes I have taken the example Consumer.java and modified example according to the requirements it's working and included the same in our spring boot application. Will this suffice the standard approach to follow for integration?

@maharanaprathapsing Since using the example code is working for you, I'll close this issue.  As @umernalla mentioned above, please use the Developer forum for **questions**.  This channel is for letting us know about any **issues** you find with the API.
