### ISSUE TITLE
EMA C++ - DataDictionary output omits negative FID range- only positive FIDs are included

### ISSUE THREAD

**Issue by zfarberov** [Refinitiv/Real-Time-SDK#225]
Hello @Real-Time-SDK C++ team,

This question was originally submitted on dev forums as 
https://community.developers.refinitiv.com/questions/100496/ema-c-print-datadictionary-containing-entries-with.html 
where the details can be found.

To summarize, in data dictionary implementation:
https://github.com/Refinitiv/Real-Time-SDK/blob/master/Cpp-C/Ema/Src/Rdm/Impl/DataDictionaryImpl.cpp
in method toString(), please see:

`const refinitiv::ema::access::EmaString&  DataDictionaryImpl::toString() const
{
_stringToString.append("Field Dictionary:\n");
 
RsslDictionaryEntry* rsslDictionaryEntry = 0;
DictionaryEntrydictionaryEntry;
 
**for (Int32 index = 0;** index <= _pRsslDataDictionary->maxFid; index++)
{
rsslDictionaryEntry = *(_pRsslDataDictionary->entriesArray + index);
 
if (rsslDictionaryEntry)
{
dictionaryEntry._pImpl->rsslDictionaryEntry(rsslDictionaryEntry);
_stringToString.append("  Fid=").append(dictionaryEntry.getFid()).append(" '").append(dictionaryEntry.getAcronym()).
append("' '").append(dictionaryEntry.getDDEAcronym()).
append("' Type=").append(dictionaryEntry.getFieldType()).
append(" RippleTo=").append(dictionaryEntry.getRippleToField()).append(" Len=").append(dictionaryEntry.getLength()).
append(" EnumLen=").append(dictionaryEntry.getEnumLength()).
append(" RwfType=").append(dictionaryEntry.getRwfType()).append(" RwfLen=").append(dictionaryEntry.getRwfLength()).append("\n");
}
}`
Consequently, negative FIDs, if present, are not included in the output of the dictionary.
Please advise,
Thanks and kind regards,
-Zoya

**Comment by ayurov2** [comment]
Hi @zfarberov, thank you for taking the time to report this and including the details on what you've found. I have opened an internal investigation JIRA for this issue.

**Comment by vlevendel** [comment]
Fixed with tag, Real-Time-SDK-2.1.0.L1. Please let us know if you have further questions or concerns.
