### ISSUE TITLE
failure to compile with GCC 11, 12 due to old version of gtest

### ISSUE THREAD

**Issue by gjvc** [Refinitiv/Real-Time-SDK#228]
**summary**
Please update the version of gtest from 1.8.1 to 1.11.0 to avoid warnings-as-errors using recent versions of GCC.

**explanation**
Real-Time-SDK 2.0.7.L2 is using version 1.8.1 of gtest.  As explained at https://github.com/google/googletest/pull/3024 this does not compile cleanly (with warnings as errors) with GCC 12 (or 11, as explained in the item)

This was fixed in gtest 1.11.0.

**see also**
https://github.com/google/googletest/pull/3024

**Comment by vlevendel** [comment]
Thank you for this issue -- we are tracking it internally and will provide the needed change in an upcoming release.

**Comment by vlevendel** [comment]
RTSDK 2.2.0.L1 addresses this issue. Please let us know if you have further concerns. Closing.
