### ISSUE TITLE
libxml2 source url is not available

### ISSUE THREAD

**Issue by tday981** [Refinitiv/Real-Time-SDK#231]
Building libxml2-2.9.12 fails since the url ftp://xmlsoft.org/libxml2/libxml2-2.9.12.tar.gz seems to be unavailable.

Official releases appear to be available here: https://download.gnome.org/sources/libxml2

When pulling the latest libxml2-2.9.12 archive, build fails due to a hash mismatch.

**Comment by ayurov2** [comment]
Hi @tday981, I appreciate you reporting this issue. I have opened an internal investigation JIRA to further review and follow up with what you have documented here.

**Comment by vlevendel** [comment]
Updated with tag Real-Time-SDK-2.0.8.L1
