### ISSUE TITLE
"Decoding of just encoded object in the same application is not supported" message when debugging EMA applications.

### ISSUE THREAD

**Issue by wasin-waeosri** [Refinitiv/Real-Time-SDK#232]
This question comes from the Developer Portal Q&A https://community.developers.refinitiv.com/questions/100852/how-can-i-pull-sofr-rics-with-java-project.html post.

When debugging EMA Java applications (like EMA Java consumer ex100_MP_Streaming example), the API shows "Decoding of just encoded object in the same application is not supported" after a debug cursor passes the following line:
```
ReqMsg reqMsg = EmaFactory.createReqMsg();
```

![emaj_debug](https://user-images.githubusercontent.com/27797359/212824914-49e464d8-a090-4a69-a1d9-1f31af848ae6.png)

The ReqMsg object works fine and can request data once I resume the application or step further. 

Based on my research, the  "Decoding of just encoded object in the same application is not supported" always appears if the application immediately retrieves data from freshly created OMM containers or messages. However, this statement just creates the ReqMsg object.

Is it expected behavior?

Best regards,

Wasin W.

**Comment by ayurov2** [comment]
Hi @wasin-waeosri,

This is expected behavior, as the IDE is attempting to call toString() method on reqMsg during debug to give you string information about the object. toString() in these scenarios will return "Decoding of just encoded object in the same application is not supported" appropriately. 

Hopefully that helps clarify why you are seeing this. Please let us know if you have additional questions here.

**Comment by wasin-waeosri** [comment]
Hi @ayurov2 

Thank you very much for the confirmation. I will update the client accordingly.

Best regards,

Wasin W.

**Comment by OleksandrKvl** [comment]
I don't know the technical reason behind this behavior but it's very surprising and inconvenient. I don't want to create both sender and receiver just to print my test `FieldList` variable. Even if it's expensive (I don't know why anyone should care about the performance of `toString` method), there should be a method to do this, just for debugging purposes.
