### ISSUE TITLE
JKS is no longer the default in JDK

### ISSUE THREAD

**Issue by addicticks-dev** [Refinitiv/Real-Time-SDK#234]
The JKS keystore file format hasn't been the default in JDK since [JEP 229](https://openjdk.org/jeps/229) was implemented into Java 9 in 2017. From that point onwards the default has been the PKCS#12 format. There really no longer was any justification for the JKS format so Oracle saw no reason to keep promoting this format. There are, however, as far as I understand no plans to remove JKS format from the JDK.

## ETA
There are some places in the ETA documentation where it says that the JKS format is the default in the JDK. This is obviously not true (since Java 9). Specifically, the Javadoc on the following classes need correction:

```text
com.refinitiv.eta.transport.EncryptionOptions
com.refinitiv.eta.transport.ServerEncryptionOptions
com.refinitiv.eta.transport.TunnelingInfo
```

Also, this need to be corrected in the ETA Developers Guide. section `10.15.1.1`, `10.15.3`, `10.15.4`.

Unfortunately (or fortunately?) the ETA implementation defaults to `JDK` and you probably don't want to change that as it may break existing ETA applications. But **ETA's default is now at odds with that of the JDK**. This requires explanation.

I also think that the library examples should stop peddling the JKS format. Or at least add comments where appropriate:  "This example uses the JKS keystore format for historical reasons. "

## EMA

I haven't found any problematic sentences in either Javadoc or the guides. It just says that the default is "JKS" (which is true as far as ETA/EMA goes).

**Comment by ayurov2** [comment]
Hi @addicticks-dev, thank you for bringing this to our attention. I have created an internal JIRA to look into this matter and update the documentation accordingly.
