### ISSUE TITLE
ETA VA C# TunnelStream

### ISSUE THREAD

**Issue by jirapongse-refinitiv** [Refinitiv/Real-Time-SDK#235]
I am uanble to find the **openTunnelStream** method in the ETA VA C# to open the tunnel stream.

In Java, the code looks like this:
```
reactorChannel.openTunnelStream(_tunnelStreamOpenOptions, errorInfo);
```

Does ETA C# support Tunnel Stream?

**Comment by ayurov2** [comment]
Hi @jirapongse-refinitiv, ETA C# does not currently support Tunnel Streams. The Readme file can be a good resource there for what features are available, and it does not list Tunnel Streams as an included feature.
