### ISSUE TITLE
Library doesn't support OpenSSL 3.1

### ISSUE THREAD

**Issue by andysCaplin** [Refinitiv/Real-Time-SDK#238]
If I specify OpenSSL 3.1 as the OpenSSL library in the initOpts.jitOpts.libcryptoName/initOpts.jitOpts.libsslName the library fails to load.
This is because of this line

```
ripcsslutils.c:495             sslFuncs.ssl_get_peer_cert = (OPENSSL_X509* (*)(const OPENSSL_SSL*))RSSL_LI_DLSYM(sslHandle, "SSL_get_peer_certificate");
```

In OpenSSL 3.1 SSL_get_peer_certificate is a #define for SSL_get1_peer_certificate().

There may be other issues as well, that was the 1st one I hit.

It would also be very useful if a library didn't load that the log said which one didn't load and why instead of just saying the SSL libraries didn't load.

**Comment by MitchellKato** [comment]
We are aware of this and will have OpenSSL 3.X support in an upcoming release.

**Comment by andysCaplin** [comment]
Is there a date for the release that supports OpenSSL 3.1 ?

**Comment by vlevendel** [comment]
This is imminent (forthcoming in our Q3 release).

**Comment by vlevendel** [comment]
2.1.2.L1 (Q3 release) has support.  Closing.
