### ISSUE TITLE
[C++] Pooled objects leak during destruction

### ISSUE THREAD

**Issue by mattgodbolt** [Refinitiv/Real-Time-SDK#240]
Found using the address sanitizer (`-fsanitize=leak`) on GCC. We use a slightly patched 2.0.8.L1.0 build, but I believe the problem is present in trunk.

During global destruction, the `g_pool` is destroyed, freeing any pooled objects. During shutdown it sets `_isFinalState = true` to prevent objects that are being destroyed from re-adding their various pooled child objects to the (being destroyed) pool.

However: this means those secondary child objects (and their children) are leaked (at least from the point of view of memory checkers like address sanitizer and valgrind).

Consider an `UpdateMsg`: during decoding it will make an `UpdateMsgDecoder` which ultimately makes a `FieldList` which will make a `FieldListDecoder`.

When the `UpdateMsg` goes out of scope, its destructor will put the `UpdateMsgDecoder` into the pool (but unlike other objects, decoder pools do not `clear()` or similar their decoder, so it will be put into the pool with its FieldList and decoder intact).

Later, during global destruction:
- `GlobalPool::~GlobalPool` sets `_isFinalState = true;` 
- it loops trying to clear its pools (even though in theory nothing should re-add free'd objects due to _isFinalState)
- eventually it clears the UpdateMsgDecoder from its pool, which calls morph() on its _payload to "free" it
- that calls `FieldList::~FieldList`, which owns its own decoders and encoders
- however, the first line of `~FieldList` checks `GlobalPool::isFinalState()` and returns without returning the objects _or freeing them_
- thus they leak

It seems that the loop in the GlobalPool destructor is "expecting" more objects to be chained back into the pool, so it seems like one ought not check the isFinalState() in all these places...OR if isFinalState is true, then the objects ought to clean up after themselves: OR maybe easier should the `Pool::returnItem` should check `isFinalState` and if so, it should free/destroy the object passed instead of re-queuing it to the GlobalPool.

**Comment by vlevendel** [comment]
This is included with tag, Real-Time-SDK-2.1.3.L1. Please let us know if you have further questions.
