### ISSUE TITLE
CURL and OpenSSL verbose log

### ISSUE THREAD

**Issue by jirapongse-refinitiv** [Refinitiv/Real-Time-SDK#241]
Can we provide configurations to generate verbose logs for CURL and OpenSSL?

Currently, it is quite hard to investigate connection issues when the issues relate to SSL errors. 

We can enable verbose logs in the SDK by modifying the SDK source code and rebuilding the libraries, such as uncommenting "#define RSSL_REST_CLIENT_VERBOSE" to enable the CURL verbose log. However, it is quite hard and inconvenient for clients to modify and rebuild the library. Moreover, the modified libraries will not be supported. 

Therefore, it is good to provide configurations to enable verbose logs in CURL and OpenSSL. in RTSDK C/C++.

Moreover, a client requested configurations to disable SSL checks in CURL and OpenSSL for testing purposes (https://community.developers.refinitiv.com/questions/106190/rtsdk-c-211l1-error-curl-failed-to-perform-the-req.html).

**Comment by MitchellKato** [comment]
We can look into providing more CURL logging, but unfortunately, at this point, ETA is providing all of the error info from OpenSSL.  There isn't more information we can provide.

We will not add any options to disable the TLS certificate checks due to security concerns.

**Comment by vlevendel** [comment]
RTSDK 2.2.0.L1 aka EMA/ETA 3.8.0.L1 addresses this issue.  Please let us know if you have further concerns. Closing.
