### ISSUE TITLE
Allow multiple configs in java jar resources

### ISSUE THREAD

**Issue by Svanar** [Refinitiv/Real-Time-SDK#246]
Hi,
I am using RTSDK for java in such scenario that I have two config files:
- EmaConfig-prd.xml
- EmaConfig-dev.xml

Unfortunately  there is a bit of extra work needed in order to make it work (like package it with docker image or compress to zip and then upzip). I think that it would be really really big improvement if there was some overloaded constructor for building config (OmmConsumerConfig in my case) that would allow either InputStream (like it is common in java) or some URL.

I am aware that similar ticket was already submitted (https://github.com/Refinitiv/Real-Time-SDK/issues/69) however it is only working with one common name.

Also I know that it is  possible to declare config via code, but I think that xml files are way more readable and maintainable.

I was checking how it looks under the hood and it would be great if we could customize that one particular line: 
https://github.com/Refinitiv/Real-Time-SDK/blob/11d3722a87c1a16ab8d59be530bcefd282e53ab2/Java/Ema/Core/src/main/java/com/refinitiv/ema/access/ConfigReader.java#L998C27-L998C27

Thanks!

**Comment by L-Karchevska** [comment]
@Svanar Thank you for reaching out to us with this suggestion! We will look into it and see what can be done.

**Comment by Svanar** [comment]
Hi, thank you for reaching out. Fingers cross that it will be added to the SDK. Looking forward to hearing good news :)

**Comment by vlevendel** [comment]
@Svanar We consider this case to be easily handled externally with appropriate packaging and do not intend to take this up at this juncture. Please let us know if you have further questions.
