### ISSUE TITLE
EMA Java: Add connection type  to OmmConsumerConfig

### ISSUE THREAD

**Issue by marcusvensson** [Refinitiv/Real-Time-SDK#248]
The OmmConsumerConfig object allows us to specify a great deal of configurations programmatically such as hostname, keystore locations etc. How ever ChannelType and  EncryptedProtocolType  can not be set meaning we are still forced to use an XML file to configure these two objects. 
It would be practical if these two also had setters on the OmmConsumerConfig along with appropriate ENUMs for their respective values

**Comment by L-Karchevska** [comment]
@marcusvensson Thank you for reporting the issue! We've created an internal Jira to deal with this request.

**Comment by vlevendel** [comment]
@marcusvensson Please view our programmatic config examples [Cons450 ](https://github.com/Refinitiv/Real-Time-SDK/blob/master/Java/Ema/Examples/src/main/java/com/refinitiv/ema/examples/training/consumer/series400/ex450_MP_QueryServiceDiscovery/Consumer.java), Cons451, Cons452, etc., for sample code to specify ChannelType and EncryptedProtocolType.

**Comment by vlevendel** [comment]
RTSDK 2.2.0.L1 addresses this issue. Please let us know if you have further concerns. Closing.
