### ISSUE TITLE
Build problem on Ubuntu 22.04.3 LTS on x86_64

### ISSUE THREAD

**Issue by NAR** [Refinitiv/Real-Time-SDK#252]
Hello!

I'm trying to build the SDK on Ubuntu 22.04.03 LTS on x86_64 hardware. I try this command from the root directory of the repo:

`cmake -DCMAKE_BUILD_TYPE=Debug -HCpp-C -Bbuild`

but I get this error:

```
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at CMakeLists.txt:13 (DEBUG_PRINT):
  Unknown CMake command "DEBUG_PRINT".


CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.22)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
```

Am I doing something wrong? I get this with `cmake` version 3.22.1 and also with `3.27.7`.

**Comment by L-Karchevska** [comment]
@NAR Thank you for raising this issue! We will run the tests and fix it as necessary in forthcoming releases.

**Comment by fogol** [comment]
@NAR I have tried your command line to run the build:

`cmake -DCMAKE_BUILD_TYPE=Debug -HCpp-C -Bbuild`

And I have got the same issue. But it seems like it is a common cmake misusing. To run cmake build you need to point cmake to the build project directory explicitly:

`cmake -DCMAKE_BUILD_TYPE=Debug -HCpp-C -Bbuild ./`

Assuming it is running from the root directory of the repo.

Now cmake build works fine.

Also we just released C/C++ support for Ubuntu and for GCC 11, and I would like to ask you to try to build it now.
If the build runs well, I will close the issue.
Thank you!

**Comment by fogol** [comment]
@NAR Please be advised, the the in-source generation build is not recommended (where you run cmake on the same directory as the source), as per cmake best practices. Recommended instruction for cmake build is here : 

[Directory Structure](https://cmake.org/cmake/help/book/mastering-cmake/chapter/Getting%20Started.html#directory-structure)
