### ISSUE TITLE
EMA CSharp: IProvider and NIProvider missing

### ISSUE THREAD

**Issue by lubomir-benus** [Refinitiv/Real-Time-SDK#254]
Hi guys,

IProvider and NIProvider are missing in the EMA CSharp implementation.
Are these going to be implemented in the future?

Thanks for the info.
Lubo

**Comment by vlevendel** [comment]
@lubomir-benus That is correct: this is planned for the next release in Q1.

**Comment by lubomir-benus** [comment]
Thanks!
