### ISSUE TITLE
Consumer application crashses in warm standby mode whenever "Force Logout From DACS" is received

### ISSUE THREAD

**Issue by thilinak** [Refinitiv/Real-Time-SDK#256]
Refer: https://community.developers.refinitiv.com/questions/111985/consumer-crashes-whenever-force-logout-from-dacs-i.html

**Comment by thilinak** [comment]
Thanks, is there a way to track the progress of issue ticket from my side?

**Comment by L-Karchevska** [comment]
@thilinak Reached out to you regarding the last question.

**Comment by vlevendel** [comment]
This is included with tag, Real-Time-SDK-2.1.3.L1. Please let us know if you have further questions.
