### ISSUE TITLE
EMA C#: LoggerClient is overriding NLOG config

### ISSUE THREAD

**Issue by michalk-gc** [Refinitiv/Real-Time-SDK#257]
Please refrain from configuring NLOG directly or better abstract away the logging. Our organization is using NLOG widely so for any application that's supposed to use both NLOG and EMA, you are overriding NLOG config and app logging stops working.

See CSharp/Ema/Src/Core/Access/LoggerClient.cs, line 117.
``                LogManager.Configuration = LoggingConf;
``

**Comment by L-Karchevska** [comment]
@michalk-gc Thank you for submitting your request. We created an internal Jira to address it.

**Comment by vlevendel** [comment]
RTSDK 2.2.0.L1 addresses this issue. Please let us know if you have further concerns. Closing.
