### ISSUE TITLE
build_type OptimizedDebug is unbuildable under Linux 

### ISSUE THREAD

**Issue by LDTV** [Refinitiv/Real-Time-SDK#266]
https://github.com/Refinitiv/Real-Time-SDK/blob/master/CMake/rcdevCompilerOptions.cmake
lines 107-123 don't contain OptimizedDebug option, which means RCDEV_C_FLAGS_INIT/RCDEV_CXX_FLAGS_INIT aren't passed further. This causes no "Linux" definition. This causes
https://github.com/Refinitiv/Real-Time-SDK/blob/master/Cpp-C/Eta/Include/Util/rtr/os.h
line 68 to be inactive. RTR_I64 is undefined, which then causes line 150 and further to fail.

A suggested solution is to add OptimizedDebug option in rcdevCompilerOptions.cmake for C and CXX builds.

**Comment by LDTV** [comment]
Fix proposition:
https://github.com/Refinitiv/Real-Time-SDK/pull/267

**Comment by L-Karchevska** [comment]
Thank you for raising this issue and the fix suggestion! We've created an internal jira to look into it.

**Comment by vlevendel** [comment]
@LDTV Please fill out a contributor agreement for us to consider this contribution. Details are found [here](https://github.com/Refinitiv/Real-Time-SDK?tab=readme-ov-file#contributing).

**Comment by vlevendel** [comment]
@LDTV We will use your pull request to handle the task. Closing this issue.
