### ISSUE TITLE
How do you configure authentication (v1) per Channel within a single OmmConsumer

### ISSUE THREAD

**Issue by paulkmoore** [Refinitiv/Real-Time-SDK#268]
I'm trying to use the WarmStandby configuration (see example ex470) but have been advised by Refinitiv that this requires a v2 account (which isn't available "yet" for our particular subscription type).  They have suggested using two v1 accounts (one per channel) as a workaround.

However, I'm struggling to see how the credentials can be set per channel. In the source (see esp com.refinitiv.ema.access.OmmConsumerConfigImpl) the authentication details are treated as global (within the context of a consumer).

Is there anyway to configure the credentials per (warmstandby) channel within a single consumer?

If not, is my only option to implement multiple consumers (with separate auth) and handle the failover etc myself?

**Comment by vlevendel** [comment]
@paulkmoore You may use the same V1 credentials for multiple connections with WarmStandby.  Please re-open if you have further concerns.
