### ISSUE TITLE
Releasing OmmConsumer resources in a multithreaded environment C++

### ISSUE THREAD

**Issue by KarevAlexandr** [Refinitiv/Real-Time-SDK#270]
I have an HTTP server (cpp-httplib library) that creates and should destroy an instance of the OmmConsumer class when processing a POST request. The library creates 10 threads to handle requests, and it feels like the OmmConsumer instance is not fully destroyed in each of them. Am I doing something wrong or is there a memory leak?

```
void handle_post_request(const httplib::Request &req, httplib::Response &res){
    try{
        OmmConsumer consumer(OmmConsumerConfig().username("username").host("127.0.0.1:1234"));
        res.set_content("OK", "application/json");
    }
    catch (const std::exception &excp){
        res.set_content("BAD", "application/json");
    }
}

int main(int argc, char *argv[]){
    httplib::Server server;
    auto endpoint = "/test/";
    auto host = "0.0.0.0";
    auto port = 8080;
    try{
        server.Post(endpoint, handle_post_request);
    }
    catch (const std::exception &e){
        return 54;
    }
    server.listen(host, port);
}
```
**Before requests:**
![image](https://github.com/Refinitiv/Real-Time-SDK/assets/34313838/a8caaeb4-565e-4acd-8451-3d898c4a82ff)

**After requests**
![image](https://github.com/Refinitiv/Real-Time-SDK/assets/34313838/f960ccdd-dc8e-461c-b894-a432ef98a638)

**Comment by L-Karchevska** [comment]
@KarevAlexandr Thank you for raising this issue and the information provided. We created an internal Jira to investigate it.

**Comment by maxstue-exx** [comment]
I've noticed something similar in the c# version 3.1.0.  where the memory grows with each request.
Inside each request we create a new consumer register a client with a batch of RICs(from 1 to 60 and sometimes even more) and after some "wait"(e.g. 10 sec) time we unregister all RICs and the consumer. Than we uninitialize the consumer, but the memory doesn't change or goes down.

**Comment by vlevendel** [comment]
> I've noticed something similar in the c# version 3.1.0. where the memory grows with each request when used in an asp.net core 6+ environment. Inside each request we create a new consumer register a client with a batch of RICs(from 1 to 60 and sometimes even more) and after some "wait"(e.g. 10 sec) time we unregister all RICs and the consumer. Than we uninitialize the consumer, but the memory doesn't change or goes down.

@maxstue-exx Please check the latest version of C# which addresses https://github.com/Refinitiv/Real-Time-SDK/issues/278 and open a new issue for any C# issue if it persists.

**Comment by algorytmus** [comment]
@KarevAlexandr We ran a complex long-running stress test with multiple consumers which pointed to no memory leaks in EMA C++. Your code is a valid usage of API; however, perhaps we can make a few recommendations (see below). Note that OmmConsumer is automatically destroyed when it is out of scope in your code snippet.  
 
If you continue to suspect a memory leak, please provide evidence of which API objects show growth over time.
 
Here are some recommendations for common use cases:

- If your goal is to service requests from an incoming connection with data obtained by an OmmConsumer, consider creating an OmmConsumer that is long running; use it for making the batch of requests and fan out responses to your incoming connections. 

- Please note that if you are interested in just request/response, you can make snapshot requests using interestAfterRefresh(false).

- For each request, if you are only interested in specific content, consider using views (or specifying which FIDs  you'd like to receive).

**Comment by vlevendel** [comment]
@KarevAlexandr Any response to above statement from @algorytmus? If you are able to provide more information, please re-open this issue with details requested. Closing since we have not heard from you in 2 weeks.
