### ISSUE TITLE
EMA Java API traces incoming messages to files only when XmlTraceToStdout=1

### ISSUE THREAD

**Issue by wasin-waeosri** [Refinitiv/Real-Time-SDK#273]
This issue is created on behalf of the client from the Q&A forum [Elektron Message API Java Edition 3.5.X traces incoming messages to files only when XmlTraceToStdout=1](https://community.developers.refinitiv.com/questions/114981/elektron-message-api-java-edition-35x-traces-incom.html) post. 

**### Problem Statement ###** 
EMA tracing of incoming messages with XmlTraceRead=1 to file(s) does not work properly.

Reactor read messages are written to files only when XmlTraceToFile=1, XmlTraceRead=1 and XmlTraceToStdout=1. Simultaneosly these messages logged to stdout as well.

It seems there is an error in the code, see https://github.com/Refinitiv/Real-Time-SDK/blob/206e4e5a3255da3afcfa75f5da151a8efef6de8e/Java/Eta/ValueAdd/src/main/java/com/refinitiv/eta/valueadd/reactor/Reactor.java#L4809

I guess it should be _reactorOptions.xmlTraceToFile() instead of _reactorOptions.xmlTracePing() in the if condition.

Documentation link: https://github.com/Refinitiv/Real-Time-SDK/blob/master/Java/Ema/Docs/EMAJ_ConfigGuide.pdf Page 12

RTDSK version is 3.7.3.0

**### Replication Steps ###**

To reproduce use the following XML configurations and compare the logs:

```
<?xml version="1.0" encoding="UTF-8"?>
<EmaConfig>
	<ConsumerGroup>
		<DefaultConsumer value="Consumer_0"/>
		<ConsumerList>
			<Consumer>
				<Name value="Consumer_0"/>
				<ChannelSet value="Channel_0"/>
				<XmlTraceRead value="1"/>
				<XmlTraceToFile value="1"/>
				<XmlTraceFileName value="ema-trace"/>
				<XmlTraceToMultipleFiles value="1"/>
				<XmlTraceMaxFileSize value="100000"/>
			</Consumer>
		</ConsumerList>
	</ConsumerGroup>
	<ChannelGroup>
		<ChannelList>
			<Channel>
				<Name value="Channel_0"/>
				<Host value="localhost"/>
				<Port value="14002"/>
			</Channel>
		</ChannelList>
	</ChannelGroup>
</EmaConfig>
```
```
<?xml version="1.0" encoding="UTF-8"?>
<EmaConfig>
	<ConsumerGroup>
		<DefaultConsumer value="Consumer_0"/>
		<ConsumerList>
			<Consumer>
				<Name value="Consumer_0"/>
				<ChannelSet value="Channel_0"/>
				<XmlTraceRead value="1"/>
				<XmlTraceToStdout value="1"/>
				<XmlTraceToFile value="1"/>
				<XmlTraceFileName value="ema-trace"/>
				<XmlTraceToMultipleFiles value="1"/>
				<XmlTraceMaxFileSize value="100000"/>
			</Consumer>
		</ConsumerList>
	</ConsumerGroup>
	<ChannelGroup>
		<ChannelList>
			<Channel>
				<Name value="Channel_0"/>
				<Host value="localhost"/>
				<Port value="14002"/>
			</Channel>
		</ChannelList>
	</ChannelGroup>
</EmaConfig>
```

**### Investigation Detail ###**

I can replicate the issue with the client's EmaConfig.xml above and ex100_MP_Streaming example on EMA Java 3.7.3.0.

With ```<XmlTraceToFile value="1"/> + <XmlTraceToStdout value="0"/>```, the API logs only outgoing messages (see api_log_toFile1_toSTDOut0.txt attachment file).
With ```<XmlTraceToFile value="1"/> + <XmlTraceToStdout value="1"/>```, the API logs both incoming and outgoint messages (see api_log_toFile1_toSTDOut1.txt attachment file)

My EmaConfig.xml is as follows:

```
<Consumer>
	<!-- Name is mandatory	-->
	<Name value="Consumer_1"/>
	<!-- Channel is optional: defaulted to "RSSL_SOCKET + localhost + 14002" -->
	<!-- Channel or ChannelSet may be specified -->
	<Channel value="Channel_1"/>
	<!-- Dictionary is optional: defaulted to "ChannelDictionary" -->
	<Dictionary value="Dictionary_2"/>
	<XmlTraceToStdout value="0"/>
	<XmlTraceToFile value="1"/>
	<XmlTraceFileName value="C:\\logs\\api.log"/>
</Consumer>
```
[api_log_toFile1_toSTDOut0.txt](https://github.com/Refinitiv/Real-Time-SDK/files/14553568/api_log_toFile1_toSTDOut0.txt)
[api_log_toFile1_toSTDOut1.txt](https://github.com/Refinitiv/Real-Time-SDK/files/14553569/api_log_toFile1_toSTDOut1.txt)

**Comment by ViktorYelizarov** [comment]
@wasin-waeosri Thank you for bringing this issue to our attention and for the details provided! We created an internal Jira to investigate it.
