### ISSUE TITLE
Availability of EMA/ETA SDK C++ as a conan package

### ISSUE THREAD

**Issue by pavik** [Refinitiv/Real-Time-SDK#274]
[conan](https://conan.io/) software package manager for C and C++ are very popular mechanism for making open-source C++ libraries available to application developers. Is it possible to make EMA/ETA C++ SDK available via conan?

**Comment by ViktorYelizarov** [comment]
Thank you for bringing this issue to our attention! We created an internal Jira to investigate it.

**Comment by MitchellKato** [comment]
At this time, we're not considering adding conan package manager support.
