### ISSUE TITLE
Memory leak in Java\WlDirectoryHandler\_directoryRefreshPool

### ISSUE THREAD

**Issue by lukeabsent** [Refinitiv/Real-Time-SDK#279]
Hi,

_directoryRefreshPool is growing over time, and keeps adding the same object over and over,
through this there is a memory leak plus some possible functional bug, cause in case of concurrent usage,
the same object may be fetched from this pool _directoryRefreshPool multiple times.
The issue seems to be present in every method that makes use of this list.
Please have a look at one function as example:
`int dispatch(ReactorErrorInfo errorInfo)`
there is this piece
```
if (!_directoryRefreshPool.isEmpty())
	        {
	        	newDirectoryRefresh = _directoryRefreshPool.poll();
```
	        	
however it can be returned **multiple** times
```
for (int i = 0; i < _stream.userRequestList().size(); i++)
            {
```
...
and within that loop is this `_directoryRefreshPool.add(newDirectoryRefresh);`

I believe it should be assured object is returned just single time to the pool plus perhaps adding some synchronization to it.
I've seen this list growing to big number and containing the same object (I didnt check every position of list though)

**Comment by vlevendel** [comment]
@lukeabsent Thank you for creating this issue. Which version of API are you using? Would you please share an application code snippet that results in memory growth over time? What is the server side your are connecting to?

**Comment by lukeabsent** [comment]
I think it was eta/ema 3.6.8.0 (maven version). 
I dont have any snippet I could share, but hopefully it should be quite obvious that there is an issue for someone analyzing these methods (methods from WlDirectoryHandler class that make use of _directoryRefreshPool field).

**Comment by vlevendel** [comment]
@lukeabsent _directoryRefreshPool increases as needed and items are returned to this pool once directory message is fanned out to application. Please note that, dispatch, which makes use of this LinkList, is protected by a global lock and the scope of the pool is limited to the WlDirectoryHandler class. The pool exists to reuse existing objects and avoid GC activity.

**Comment by soranat** [comment]
@lukeabsent

The dispatch(ReactorErrorInfo errorInfo) function will be fixed to return the DirectoryRefresh object **only once t**o the _directoryRefreshPool as same as the other methods which uses the _directoryRefreshPool to reuse the DirectoryRefresh object.

**Comment by vlevendel** [comment]
@lukeabsent A fix will be provided in a future release.

**Comment by lukeabsent** [comment]
@vlevendel @soranat 
Thank you
