### ISSUE TITLE
UpdateMsg::toString() shows crap for "partial update"

### ISSUE THREAD

**Issue by miczuc** [Refinitiv/Real-Time-SDK#282]
Hello, I made a test for a "partial update". For this I built an "interactive provider", by using
your example from your directory Cpp-C/Ema/Examples/Training/IProvider/100_Series/100_MP_Streaming.
I changed the main() function in IProvider.cpp slightly, by adding two fields with ids 315 and 105,
as follows:

int main()
{
	try
	{
		AppClient appClient;

		OmmProvider provider( OmmIProviderConfig().port( "14002" ), appClient );
		
		char partUpd[] = {0x1B, 0x5B, '9', 0x60, '1', '2', '3', '4', '5'};

		EmaBuffer testBuf(partUpd, sizeof(partUpd));

		while ( itemHandle == 0 ) sleep(1000);
		
		for ( Int32 i = 0; i < 60; i++ )
		{
			provider.submit( UpdateMsg().payload( FieldList().
					addReal( 22, 3391 + i, OmmReal::ExponentNeg2Enum ).
					addReal( 30, 10 + i, OmmReal::Exponent0Enum ).
					addAscii(315, "--+--+--+--+--+--+--+--+--+--+--+--  Row  1  --+--+--+--+--+--+--+--+--+--+--+--").
					addRmtes(105, testBuf).
					complete() ), itemHandle );
					
			sleep( 1000 );
		}
	}
	catch ( const OmmException& excp )
	{
		cout << excp << endl;
	}
	
	return 0;
}

For connecting to the interactive provider and displaying the received messages, I built the
example consumer from your directory Cpp-C/Ema/Examples/Training/Consumer/100_Series/100_MP_Streaming .

This is the output for a received update message:
>>>>
UpdateMsg
    streamId="5"
    domain="MarketPrice Domain"
    updateTypeNum="0"
    name="IBM.N"
    serviceId="1"
    serviceName="DIRECT_FEED"
    Payload dataType="FieldList"
        FieldList
            FieldEntry fid="22" name="BID" dataType="Real" value="33.91"
            FieldEntry fid="30" name="BIDSIZE" dataType="Real" value="10"
            FieldEntry fid="315" name="ROW80_1" dataType="Rmtes" value="--+--+--+--+--+--+--+--+--+--+--+--  Row  1  --+--+--+--+--+--+--+--+--+--+--+--"
            FieldEntry fid="105" name="BCKGRNDPAG" dataType="Rmtes" value="--+--+--+12345"
        FieldListEnd

    PayloadEnd
UpdateMsgEnd
<<<<

The value displayed for field 105 obviously contains some characters of the preceding field 315.
Since field 105 contains an escape sequence, it is questionable, what to output for the field in toString() .
However, what is displayed in this example, is definitely wrong.

**Comment by fogol** [comment]
@miczuc Thank you for bringing this to our attention. We will investigate the issue. It will be fixed in further releases.

**Comment by fogol** [comment]
@miczuc The point is that you will see garbled data because it is a _partial update_ if you print the update without creating an application level cache and applying updates to that cache. As mentioned, please refer to Example Cons310.

**Comment by miczuc** [comment]
I cannot influence what is printed by UpdateMsg::toString() . If the class UpdateMsg provides a method toString(), then the implementation of this method is responsible for what is outputted by the method, whatever the contents of the message may be. So the method UpdateMsg::toString() must take into account, that there may be fields containing partial updates and, in that case, output some useful information for these instead of garbage. In my option you just do not want to solve the problem, that's all.

**Comment by fogol** [comment]
@miczuc The toString functionality is provided to you as a helper function and diagnostic tool. We do not intend to change scope of this function. If you have further questions about partial updates, please reach out on our Developer Portal: https://developers.lseg.com/
