### ISSUE TITLE
The CMAKE file doesn't work on VS2022 Version 17.10.2 with MSVC 1940

### ISSUE THREAD

**Issue by jirapongse-refinitiv** [Refinitiv/Real-Time-SDK#285]
The problem should be in the https://github.com/Refinitiv/Real-Time-SDK/blob/master/CMake/rcdevSystemInfo.cmake#L557 file. 

		DEBUG_PRINT(MSVC_TOOLSET_VERSION)
		if (MSVC_VERSION GREATER_EQUAL 1930 AND MSVC_VERSION LESS_EQUAL 1939)
			set(_compilerVer "143")
			set(_msvcVer "17")
			set(_msvcYear "2022")

1939 should be changed to 1940. 

The client said that his VS2022 uses MSVC 1941. 

https://en.wikipedia.org/wiki/Microsoft_Visual_C%2B%2B

**Comment by fogol** [comment]
@jirapongse-refinitiv Thank you for bringing this to our attention. It will be fixed in further releases.

**Comment by vlevendel** [comment]
@jirapongse-refinitiv This is addressed with RTSDK 2.2.2.L1. Please let us know if there are further issues.
