### ISSUE TITLE
Ema C++ : OmmConsumerClient, OmmConsumerErrorClient forbid copy-constructor for no reason

### ISSUE THREAD

**Issue by miczuc** [Refinitiv/Real-Time-SDK#286]
In a consumer application the classes OmmConsumerClient, OmmConsumerErrorClient must be subclassed 
in order to handle messages / events through reimplemented virtual callback methods e.g. onRefreshMsg().
However these classes have a disabled copy-constructor and assignment operator, e.g.:

private :
	OmmConsumerClient( const OmmConsumerClient& );
	OmmConsumerClient& operator=( const OmmConsumerClient& );

This is complete senseless, since the classes do not contain any data members. It forces the application to use non-copyable classes as handler classes, although it is not necessary. This is an unwanted and unnecessary restriction.

**Comment by fogol** [comment]
@miczuc Thank you for bringing this to our attention. We will investigate the issue to provide the solution.

**Comment by vlevendel** [comment]
Fixed with version Real-Time-SDK-2.2.3.L1. Please reopen if there are additional concerns.
