### ISSUE TITLE
EMA C++: Post message received in provider does not contain service name set in consumer

### ISSUE THREAD

**Issue by miczuc** [Refinitiv/Real-Time-SDK#296]
Hello,

I tested a little with Post messages and noticed, that a Post message received in the provider
does not contain the service name, that has been set in the consumer in the sent post message.
The method hasServiceName() returns false on the provider for the post message.
However, the received Post message contains the corresponding service id.
This can be easily verified with the examples 
Consumer/300_Series/340_MP_OnStreamPost
Consumer/300_Series/341_MP_OffStreamPost
IProvider/300_Series/340_MP_Posting

by using 'serviceName("DIRECT_FEED")' on the consumer for setting a service name in the post message.

Regards, Michael Zuck

**Comment by miczuc** [comment]
Hi, here is a suggestion how the problem could be solved:
In MarketItemHandler::itemCallback() add the instruction
ommServerBaseImpl->_postMsg.getDecoder().setServiceName((*serviceNamePtr)->c_str(), (*serviceNamePtr)->length());
in the block for case RSSL_MC_POST.
For this to work the method PostMsgDecoder::setServiceName() must be reimplemented, like in ReqMsgDecoder,
and in PostMsg.h class MarketItemHandler must be declared as friend, like in ReqMsg.h .

Regards, Michael Zuck

**Comment by vlevendel** [comment]
@miczuc Thanks for your input. I have a fix working and it will be available in an upcoming release.

**Comment by miczuc** [comment]
Hello, I think you misunderstood. The problem is, that the post message presented to the application on the provider side via OmmProviderClient::onPostMsg(const PostMsg & postMsg, const OmmProviderEvent & event) never contains a service name.

**Comment by vlevendel** [comment]
@miczuc The code snippet above is from onPostMsg of IProv340. It is retrieving the service name from the postMsg in onPostMsg to add to the ackMsg.  If you have any more concerns, do reach out.

**Comment by miczuc** [comment]
If you add "ackMsg.serviceName(postMsg.getServiceName());" in the IProv340 example, you get an exception on the provider: "Exception Type='OmmInvalidUsageException', Text='Attempt to getServiceName() while it is NOT set.', ErrorCode='-4048'".
And this is the subject of this issue: What ever you do, the service name is always missing in the received post message.
Do you understand this or not ???

**Comment by soranat** [comment]
The PostMsg will be fixed in order to convey the service name to the application so EMA will not throw 'OmmInvalidUsageException' when calling the postMsg.getServiceName() method.

**Comment by miczuc** [comment]
For the 10th time: The issue is, that there is no service name in the post message. This has **nothing** to do with the AckMsg. This problem will remain, even if you delete my messages.  Then ignore this issue, do nothing or close or whatever.

**Comment by vlevendel** [comment]
I have a fix working and it will be available in an upcoming release.

This should work after our fix is made available to you:
ackMsg.serviceName(postMsg.getServiceName());

**Comment by vlevendel** [comment]
Addressed with version Real-Time-SDK-2.2.3.L1

**Comment by miczuc** [comment]
Retested in version 2.3.0, works. Service name set on consumer side is available now in the PostMsg passed to onPostMsg( ) on provider side. thx.
