### ISSUE TITLE
EMA C++: Method setServiceName() in PostMsgDecoder is a non-operation

### ISSUE THREAD

**Issue by miczuc** [Refinitiv/Real-Time-SDK#297]
Hello,

I noticed the following small deficiency: The class PostMsgDecoder inherits the virtual method
"setServiceName(const char *, UInt32, bool nullTerm = true)" from class Decoder,
where it is predefined with an empty body. However, there exists a use-case of this method in
PostMsg::PostMsg(const PostMsg& other). The result may be, that the copied PostMsg lacks the service name.
Because of issue #296 ("EMA C++: Post message received in provider does not contain service name set in consumer")
I could not check this.

Regards, Michael Zuck

**Comment by vlevendel** [comment]
@miczuc This does not appear to be a problem in code where #295 and #296 are addressed. Please reopen if you find otherwise.

**Comment by miczuc** [comment]
Hello, I do not understand, why you close this issue. The copy constructor PostMsg::PostMsg(const PostMsg& other) will not copy the service name. But this cannot be verified, because the service name is never set in a received post message on the provider, even if the consumer sets a service name. These are two independent bugs!

**Comment by miczuc** [comment]
Had a look at version 2.3.0, there the problem is solved, probably as part of the solution for issues 295 and 296. thx.
