### ISSUE TITLE
Decoder placement new tricks: std::launder needed to ensure correctness

### ISSUE THREAD

**Issue by DuncanSands** [Refinitiv/Real-Time-SDK#59]
The Ema library decoder implementation uses placement new to write objects of one class on top of objects of another class (see Decoder::create and StaticDecoder::create).  I tracked down crashes in MapDecoder::~MapDecoder() on program exit when compiling Ema using GCC with link-time optimization to the use of placement new in StaticDecoder::create.  What happens is that in

```
MapDecoder::~MapDecoder()
{
        if ( _atExit )
        {
                if ( _elementListSetDef ) 
                        delete _elementListSetDef;

                if ( _fieldListSetDef )
                        delete _fieldListSetDef;
        }
        else
        {
                if ( _elementListSetDef ) 
                        g_pool._elementListSetDefPool.returnItem( _elementListSetDef );

                if ( _fieldListSetDef )
                        g_pool._fieldListSetDefPool.returnItem( _fieldListSetDef );
        }

        StaticDecoder::morph( &_key, DataType::NoDataEnum );
        StaticDecoder::morph( &_load, DataType::NoDataEnum ); 
        StaticDecoder::morph( &_summary, DataType::NoDataEnum );
}
```

the optimizers remove the three calls to StaticDecoder::morph.  If you know how this stuff works then you will understand how removing these can cause a crash immediately afterwards (in my case, the NoDataImpl destructor was run on _summary even though it was created earlier, using placement new, as a FieldList; normally the morph call would have turned it back into a NoDataImpl, avoiding this destructor mismatch).

Were the optimizers wrong to do this?  What Ema is doing is essentially the same as the second example in https://miyuki.github.io/2016/10/21/std-launder.html, see also the test cases in https://gcc.gnu.org/ml/libstdc++/2016-10/msg00194.html.  It seems likely that the optimizers are indeed allowed to remove the calls, i.e. the Ema code is wrong.  To make it correct, std::launder is needed.  The following patch fixed the crash for me:

```
--- a/Ema/Src/Access/Impl/StaticDecoder.cpp
+++ b/Ema/Src/Access/Impl/StaticDecoder.cpp
@@ -143,7 +143,7 @@ void StaticDecoder::morph( Data* data, DataType::DataTypeEnum dType )
        }
 }

-void StaticDecoder::create( Data* data, DataType::DataTypeEnum dType )
+void StaticDecoder::create( Data*& data, DataType::DataTypeEnum dType )
 {
        switch ( dType )
        {
@@ -250,4 +260,6 @@ void StaticDecoder::create( Data* data, DataType::DataTypeEnum dType )
                new (data) OmmError();
                break;
        }
+
+       data = std::launder(data);
 }
diff --git a/Ema/Src/Access/Impl/StaticDecoder.h b/Ema/Src/Access/Impl/StaticDecoder.h
index fa7e5d710c..16f6825314 100755
--- a/elektron-latest/Ema/Src/Access/Impl/StaticDecoder.h
+++ b/elektron-latest/Ema/Src/Access/Impl/StaticDecoder.h
@@ -66,7 +66,7 @@ public :
        // helper utilities
        static void morph( Data* , DataType::DataTypeEnum );

-       static void create( Data* , DataType::DataTypeEnum );
+       static void create( Data*& , DataType::DataTypeEnum );
 };

 }
```

I didn't audit the Ema code for other places that might need std::launder, however Decoder::create seems likely to be one such place.

Unfortunately, I don't see how you can apply this patch, as std::launder is not widely available (it's from C++17).  With GCC you can emulate this C++17 feature using this code:

```
namespace std
{
  template <typename T>
  T *
  launder (T *p)
  {
    return __builtin_launder (p);
  }
}
```

but that's not going to work for other compilers, or even for older versions of GCC.  I'm reporting this anyway as documentation for others hitting this issue, and as it seems like something you should be aware of.

**Comment by bberner** [comment]
Thank you for your feedback. A JIRA issue has been created and the issue is being investigated. We’ll let you know if we have any problems reproducing the issue.

**Comment by vlevendel** [comment]
Rejecting because we can't use non-backwards compatible new features of C++ compiler.
