### ISSUE TITLE
ETA static /MT

### ISSUE THREAD

**Issue by triaxia** [Refinitiv/Real-Time-SDK#71]
Can you please let me know how I can build a static library for ETA.  i.e. without dragging in MS runtime dlls on a Windows platform.

I can create a project that builds a lib file, but have a no idea what files are to be included. 

I need it for subscribes and contributes to Reuters via a RSSL connection.

**Comment by vlevendel** [comment]
We currently provide MDd and MD and do not have plans to create an MT static lib for ETA.
