### ISSUE TITLE
how to encode multipart messages

### ISSUE THREAD

**Issue by donghao-hao** [Refinitiv/Real-Time-SDK#87]
We are trying to encoding LEVEL2 data, like SYMBOL LIST, via JAVA EMA.
I am not clear on how big one message should be, and what mechanism I can take in EMA to split one message to many parts. Can you share us an example of encoding refresh message with multiple part.

**Comment by bberner** [comment]
Refer to the dictionary example (iprovider.series300.example332__Dictionary__UserControl) and look at the processDictionaryRequest() method. This method sends out the field dictionary as multi-part. Note the RefreshMsg.complete(false or true) method is used to indicate the parts of a multi-part refresh. The first parts of a multi-part refresh have RefreshMsg.complete(false) and last part has RefreshMsg.complete(true).

**Comment by donghao-hao** [comment]
Thanks a lot @bberner

**Comment by donghao-hao** [comment]
It seems that key function is encodeFieldDictionary, and multiple part is determined by last param fragmentatioonSize.  Do you know the common way, except encoding the dictionary. @bberner

**Comment by bberner** [comment]
It's arbitrary when to call RefreshMsg.complete(false) or RefreshMsg.complete(true). The dictionary example used fragmentationSize for deciding when the RefreshMsg is complete. A simple symbol list example could send each RefreshMsg with a Map of one MapEntry. RefreshMsg.complete(true) would be called on the last MapEntry. You could also send more than one MapEntry per RefreshMsg calling RefreshMsg.complete(false) on every RefreshMsg except the last one. The last set of MapEntries sent in the RefreshMsg would call RefreshMsg.complete(true).

**Comment by donghao-hao** [comment]
Thank you very much.
